"""
spotify_service.py
Handles playlist creation + safe Spotify operations
"""

import random
import time

from log import log


# ---------------------------------------------------
# SAFE REQUEST WRAPPER
# ---------------------------------------------------

def safe_spotify_call(func, *args, retries=3, **kwargs):
    """
    Retry wrapper for Spotify API calls.
    Handles temporary 429 rate limits.
    """

    for attempt in range(retries):

        try:
            return func(*args, **kwargs)

        except Exception as e:

            error = str(e)

            # Spotify rate limit
            if "429" in error:

                wait_time = 3 + attempt * 2

                log(
                    "WARNING",
                    "spotify_rate_limit",
                    f"Retrying in {wait_time}s"
                )

                time.sleep(wait_time)
                continue

            raise

    raise Exception("Spotify API failed after retries")


# ---------------------------------------------------
# CREATE PLAYLIST
# ---------------------------------------------------

def create_playlist(sp, vibe_text):
    """
    Create playlist on Spotify account.
    """

    me = safe_spotify_call(sp.me)

    playlist_name = generate_playlist_name(vibe_text)

    description = (
        f"Generated by K_WALAH • vibe: {vibe_text}"
    )

    playlist = safe_spotify_call(
        sp.user_playlist_create,
        me["id"],
        playlist_name,
        public=False,
        description=description
    )

    log(
        "INFO",
        "playlist_created",
        playlist_name,
        user=me["id"]
    )

    return playlist


# ---------------------------------------------------
# ADD TRACKS
# ---------------------------------------------------

def add_tracks_to_playlist(sp, playlist_id, uris):
    """
    Upload tracks in safe batches.
    Spotify max = 100 per request.
    """

    if not uris:
        return

    total = len(uris)

    for i in range(0, total, 100):

        batch = uris[i:i + 100]

        safe_spotify_call(
            sp.playlist_add_items,
            playlist_id,
            batch
        )

        time.sleep(0.15)


# ---------------------------------------------------
# PLAYLIST NAME GENERATOR
# ---------------------------------------------------

PLAYLIST_PREFIXES = [
    "late night",
    "midnight",
    "motion",
    "blurred",
    "afterhours",
    "neon",
    "static",
    "echoes",
    "liminal",
    "empty roads",
    "headlights",
    "distant memories",
    "soft chaos",
    "sleep deprived",
    "rain signals",
    "ghost drive",
]

PLAYLIST_SUFFIXES = [
    "sessions",
    "radio",
    "tapes",
    "fm",
    "vol.1",
    "archive",
    "mix",
    "playlist",
    "thoughts",
    "dreamscape",
    "loop",
    "collection",
]


def generate_playlist_name(vibe_text):
    """
    Generate less-generic playlist names.
    """

    vibe_text = (vibe_text or "").strip()

    if len(vibe_text) > 40:
        vibe_text = vibe_text[:40]

    formats = [

        lambda: vibe_text,

        lambda: f"{random.choice(PLAYLIST_PREFIXES)}",

        lambda: f"{vibe_text} • {random.choice(PLAYLIST_SUFFIXES)}",

        lambda: f"{random.choice(PLAYLIST_PREFIXES)} • {vibe_text}",

        lambda: f"{random.choice(PLAYLIST_PREFIXES)} {random.choice(PLAYLIST_SUFFIXES)}",
    ]

    return random.choice(formats)()
