import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type Config = {
  baseUrl: string;
  spotifyUserId: string;
  token: string;
  outDir: string;
  timeoutMs: number;
  expectedDeploymentVersion: string | null;
  baselinePath: string | null;
};

type PromptSpec = {
  prompt: string;
  requestedLength: number;
  baseline: {
    density: number;
    latencyMs: number;
    trustScore: number;
  };
  allowedFamilies: string[];
  blockedFamilies: string[];
  requiredEra?: string;
};

type GuardTrack = {
  id?: string;
  trackId?: string;
  name?: string;
  trackName?: string;
  artist?: string;
  artistName?: string;
  genreFamily?: string | null;
  genrePrimary?: string | null;
  genres?: string[] | null;
  releaseYear?: number | null;
};

type PromptResult = {
  prompt: string;
  latencyMs: number;
  count: number;
  fallbackUsed: boolean;
  trustScore: number;
  semanticDrift: boolean;
  drift: {
    drift_level: "NONE" | "PARTIAL" | "FULL";
    violations: string[];
    trust_impact: "LOW" | "MEDIUM" | "HIGH";
  };
  candidateHealth: {
    prompt: string;
    initial_pool_size: number;
    post_filter_size: number;
    survival_rate: number;
    primary_loss_reason: string;
    density_risk: "LOW" | "MEDIUM" | "HIGH";
  };
  latencyBreakdown: {
    queue: number;
    deps: number;
    candidate_fetch: number;
    scoring: number;
    fallback: number;
    response_build: number;
  };
  unaccountedLatency: number;
  missingTimeline: boolean;
  topGenres: Record<string, number>;
  topEras: Record<string, number>;
  sourceMode: string | null;
  error: string | null;
};

const PROMPTS: PromptSpec[] = [
  {
    prompt: "gym 2000s pop punk workout",
    requestedLength: 30,
    baseline: { density: 10, latencyMs: 20_597, trustScore: 100 },
    allowedFamilies: ["rock", "unknown"],
    blockedFamilies: ["hip_hop", "country", "classical", "christmas"],
    requiredEra: "2000s",
  },
  {
    prompt: "gym heavy lifting intense",
    requestedLength: 30,
    baseline: { density: 9, latencyMs: 12_366, trustScore: 100 },
    allowedFamilies: ["rock", "metal", "electronic", "unknown", "indie", "blues", "reggae", "soundtrack", "soul"],
    blockedFamilies: ["hip_hop", "country", "classical", "christmas"],
  },
  {
    prompt: "gym cardio upbeat",
    requestedLength: 30,
    baseline: { density: 4, latencyMs: 11_209, trustScore: 100 },
    allowedFamilies: ["pop", "rock", "electronic", "indie", "unknown", "metal", "soundtrack", "reggae", "blues"],
    blockedFamilies: ["hip_hop", "country", "classical", "christmas"],
  },
  {
    prompt: "gym angry rock",
    requestedLength: 30,
    baseline: { density: 30, latencyMs: 9_408, trustScore: 100 },
    allowedFamilies: ["rock", "unknown"],
    blockedFamilies: ["hip_hop", "country", "classical", "christmas"],
  },
];

function usage(): never {
  process.stderr.write([
    "Usage:",
    "  npm run regression:playlists -- --base-url URL --spotify-user-id USER_ID --token TOKEN",
    "",
    "Options:",
    "  --out DIR                         Output directory (default reports/playlist-regression/latest)",
    "  --timeout-ms N                    Per-request timeout (default 30000)",
    "  --baseline FILE                   Optional baseline JSON generated by this script",
    "  --expected-deployment-version SHA Expected deployed commit",
  ].join("\n") + "\n");
  process.exit(2);
}

function argValue(args: string[], name: string): string | null {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] ?? null : null;
}

function parseConfig(args: string[]): Config {
  if (args.includes("--help") || args.includes("-h")) usage();
  const baseUrl = argValue(args, "--base-url") ?? process.env["API_BASE_URL"] ?? process.env["PLAYLIST_EVAL_BASE_URL"] ?? process.env["APP_URL"] ?? "";
  const spotifyUserId = argValue(args, "--spotify-user-id") ?? process.env["SPOTIFY_USER_ID"] ?? process.env["PLAYLIST_EVAL_SPOTIFY_USER_ID"] ?? "";
  const token = argValue(args, "--token") ?? process.env["PLAYLIST_EVAL_TOKEN"] ?? "";
  if (!baseUrl) throw new Error("Base URL is required.");
  if (!spotifyUserId) throw new Error("Spotify user id is required.");
  if (!token) throw new Error("PLAYLIST_EVAL_TOKEN is required.");
  return {
    baseUrl: baseUrl.replace(/\/+$/, ""),
    spotifyUserId,
    token,
    outDir: argValue(args, "--out") ?? "reports/playlist-regression/latest",
    timeoutMs: Number(argValue(args, "--timeout-ms") ?? 30_000),
    expectedDeploymentVersion: argValue(args, "--expected-deployment-version") ?? process.env["EXPECTED_DEPLOYMENT_VERSION"] ?? null,
    baselinePath: argValue(args, "--baseline"),
  };
}

function localGitHead(): string {
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}

function versionsMatch(expected: string, actual: string): boolean {
  if (!expected || !actual || expected === "unknown" || actual === "unknown") return true;
  return expected === actual || expected.startsWith(actual) || actual.startsWith(expected);
}

async function fetchJson(url: string, init: RequestInit, timeoutMs: number): Promise<{ status: number; body: Record<string, unknown> }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(url, { ...init, signal: controller.signal });
    const body = await response.json().catch(() => ({})) as Record<string, unknown>;
    return { status: response.status, body };
  } finally {
    clearTimeout(timer);
  }
}

async function preflight(config: Config): Promise<string> {
  const ping = await fetchJson(`${config.baseUrl}/api/eval/ping`, { method: "GET" }, 15_000);
  const commit = String(ping.body["commit"] ?? "unknown");
  const expected = config.expectedDeploymentVersion ?? localGitHead();
  if (!versionsMatch(expected, commit)) {
    throw new Error(`Deployment commit mismatch: expected ${expected}, got ${commit}`);
  }
  return commit;
}

function percentile(values: number[], pct: number): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const index = Math.min(sorted.length - 1, Math.max(0, Math.ceil((pct / 100) * sorted.length) - 1));
  return sorted[index] ?? 0;
}

function genreFamily(track: GuardTrack): string {
  return String(track.genreFamily ?? track.genrePrimary ?? track.genres?.[0] ?? "unknown").toLowerCase();
}

function eraBucket(year: unknown): string {
  if (typeof year !== "number" || !Number.isFinite(year)) return "unknown";
  return `${Math.floor(year / 10) * 10}s`;
}

function increment(map: Record<string, number>, key: string): void {
  map[key] = (map[key] ?? 0) + 1;
}

function numberFromRecord(record: Record<string, unknown> | undefined, key: string): number {
  const value = record?.[key];
  return typeof value === "number" && Number.isFinite(value) ? value : 0;
}

function objectFrom(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
}

function timelineReport(body: Record<string, unknown>): {
  timeline: Record<string, unknown>;
  unaccounted: number;
  breakdown: PromptResult["latencyBreakdown"];
  missingTimeline: boolean;
} {
  const diagnostics = objectFrom(body["generationDiagnostics"]);
  const productionTimeline = objectFrom(diagnostics?.["productionTimeline"]);
  const timeline = objectFrom(productionTimeline?.["timeline"]) ?? {};
  const queue = Math.max(0, numberFromRecord(timeline, "worker_acquired") - numberFromRecord(timeline, "queue_entered"));
  const deps = Math.max(0, numberFromRecord(timeline, "deps_loaded"));
  const candidateFetch = Math.max(0, numberFromRecord(timeline, "candidate_fetch_end") - numberFromRecord(timeline, "candidate_fetch_start"));
  const scoring = Math.max(0, numberFromRecord(timeline, "scoring_end") - numberFromRecord(timeline, "scoring_start"));
  const required = [
    "request_received",
    "queue_entered",
    "worker_acquired",
    "deps_loaded",
    "candidate_fetch_start",
    "candidate_fetch_end",
    "scoring_start",
    "scoring_end",
    "v3_entry",
  ];
  return {
    timeline,
    unaccounted: numberFromRecord(productionTimeline, "unaccounted_time_ms"),
    breakdown: {
      queue,
      deps,
      candidate_fetch: candidateFetch,
      scoring,
      fallback: 0,
      response_build: 0,
    },
    missingTimeline: required.some((key) => timeline[key] === null || timeline[key] === undefined),
  };
}

function candidateShape(body: Record<string, unknown>): Record<string, unknown> {
  const diagnostics = objectFrom(body["generationDiagnostics"]);
  const fastPath = objectFrom(diagnostics?.["performanceFastPath"]);
  return objectFrom(fastPath?.["preScoringCandidateShape"]) ?? {};
}

function candidateHealth(prompt: string, shape: Record<string, unknown>): PromptResult["candidateHealth"] {
  const initial = numberFromRecord(shape, "inputCount");
  const post = numberFromRecord(shape, "outputCount");
  const strict = numberFromRecord(shape, "strictConstrainedCount");
  const hard = numberFromRecord(shape, "hardConstrainedCount");
  const exact = numberFromRecord(shape, "explicitGenreEraConstrainedCount");
  const adjacent = numberFromRecord(shape, "adjacentGenreEraConstrainedCount");
  const genericGym = numberFromRecord(shape, "genericGymFamilySafeCount");
  const survival = initial > 0 ? post / initial : 0;
  const sourceMode = String(shape["sourceMode"] ?? "unknown");
  const primaryLoss =
    strict === 0 && hard === 0 && exact === 0 && adjacent === 0
      ? "strict_constraint_sparsity"
      : genericGym > 0 && sourceMode === "generic_gym_family_safe"
        ? "semantic_prune_required"
        : sourceMode;
  const densityRisk = post >= 240 && survival >= 0.02 ? "LOW" : post >= 90 ? "MEDIUM" : "HIGH";
  return {
    prompt,
    initial_pool_size: initial,
    post_filter_size: post,
    survival_rate: Math.round(survival * 1000) / 1000,
    primary_loss_reason: primaryLoss,
    density_risk: densityRisk,
  };
}

function driftFor(spec: PromptSpec, tracks: GuardTrack[]): PromptResult["drift"] {
  const violations: string[] = [];
  const allowed = new Set(spec.allowedFamilies);
  for (const track of tracks) {
    const family = genreFamily(track);
    if (spec.blockedFamilies.includes(family)) violations.push(`blocked_genre:${family}`);
    if (allowed.size > 0 && !allowed.has(family)) violations.push(`unexpected_genre:${family}`);
    if (spec.requiredEra && eraBucket(track.releaseYear) !== spec.requiredEra) violations.push(`era:${eraBucket(track.releaseYear)}`);
  }
  const uniqueViolations = [...new Set(violations)];
  const ratio = tracks.length > 0 ? uniqueViolations.length / tracks.length : 1;
  const driftLevel = uniqueViolations.length === 0 ? "NONE" : ratio >= 0.5 ? "FULL" : "PARTIAL";
  return {
    drift_level: driftLevel,
    violations: uniqueViolations,
    trust_impact: driftLevel === "NONE" ? "LOW" : driftLevel === "PARTIAL" ? "MEDIUM" : "HIGH",
  };
}

function trustScore(spec: PromptSpec, tracks: GuardTrack[], fallbackUsed: boolean, latencyMs: number, missingTimeline: boolean, unaccounted: number): number {
  const drift = driftFor(spec, tracks);
  let score = 100;
  if (tracks.length === 0) score -= 100;
  if (fallbackUsed) score -= 25;
  if (latencyMs > 30_000) score -= 30;
  if (missingTimeline || unaccounted > 0) score -= 20;
  if (drift.drift_level === "PARTIAL") score -= 35;
  if (drift.drift_level === "FULL") score -= 70;
  return Math.max(0, score);
}

async function postGenerate(config: Config, spec: PromptSpec): Promise<PromptResult> {
  const started = Date.now();
  try {
    const response = await fetchJson(`${config.baseUrl}/api/generate?audit=1`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-kwalify-evaluation-token": config.token,
      },
      body: JSON.stringify({
        vibe: spec.prompt,
        mode: "balanced",
        length: spec.requestedLength,
        varietyBoost: true,
        auditMode: true,
        spotifyUserId: config.spotifyUserId,
      }),
    }, config.timeoutMs);
    const elapsed = Date.now() - started;
    const tracks = Array.isArray(response.body["tracks"]) ? response.body["tracks"] as GuardTrack[] : [];
    const timeline = timelineReport(response.body);
    timeline.breakdown.response_build = Math.max(0, elapsed - numberFromRecord(timeline.timeline, "scoring_end"));
    const genres: Record<string, number> = {};
    const eras: Record<string, number> = {};
    for (const track of tracks) {
      increment(genres, genreFamily(track));
      increment(eras, eraBucket(track.releaseYear));
    }
    const fallbackUsed = response.body["fastFallback"] === true || objectFrom(response.body["generationDiagnostics"])?.["fallbackLevel"] !== "none";
    const drift = driftFor(spec, tracks);
    const shape = candidateShape(response.body);
    return {
      prompt: spec.prompt,
      latencyMs: elapsed,
      count: tracks.length,
      fallbackUsed,
      trustScore: trustScore(spec, tracks, fallbackUsed, elapsed, timeline.missingTimeline, timeline.unaccounted),
      semanticDrift: drift.drift_level !== "NONE",
      drift,
      candidateHealth: candidateHealth(spec.prompt, shape),
      latencyBreakdown: timeline.breakdown,
      unaccountedLatency: timeline.unaccounted,
      missingTimeline: timeline.missingTimeline,
      topGenres: genres,
      topEras: eras,
      sourceMode: typeof shape["sourceMode"] === "string" ? shape["sourceMode"] : null,
      error: response.status >= 400 ? String(response.body["error"] ?? response.status) : null,
    };
  } catch (err) {
    const elapsed = Date.now() - started;
    return {
      prompt: spec.prompt,
      latencyMs: elapsed,
      count: 0,
      fallbackUsed: false,
      trustScore: 0,
      semanticDrift: true,
      drift: { drift_level: "FULL", violations: ["request_failed"], trust_impact: "HIGH" },
      candidateHealth: { prompt: spec.prompt, initial_pool_size: 0, post_filter_size: 0, survival_rate: 0, primary_loss_reason: "request_failed", density_risk: "HIGH" },
      latencyBreakdown: { queue: 0, deps: 0, candidate_fetch: 0, scoring: 0, fallback: 0, response_build: 0 },
      unaccountedLatency: 0,
      missingTimeline: true,
      topGenres: {},
      topEras: {},
      sourceMode: null,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

async function loadBaseline(config: Config): Promise<Record<string, PromptSpec["baseline"]>> {
  if (!config.baselinePath) return Object.fromEntries(PROMPTS.map((prompt) => [prompt.prompt, prompt.baseline]));
  const raw = JSON.parse(await readFile(config.baselinePath, "utf8")) as Record<string, unknown>;
  const rows = Array.isArray(raw["prompts"]) ? raw["prompts"] as Array<Record<string, unknown>> : [];
  const baseline = Object.fromEntries(PROMPTS.map((prompt) => [prompt.prompt, prompt.baseline]));
  for (const row of rows) {
    const prompt = String(row["prompt"] ?? "");
    if (!prompt) continue;
    baseline[prompt] = {
      density: numberFromRecord(row, "count"),
      latencyMs: numberFromRecord(row, "latencyMs"),
      trustScore: numberFromRecord(row, "trustScore"),
    };
  }
  return baseline;
}

async function main(): Promise<void> {
  const config = parseConfig(process.argv.slice(2));
  const deployedCommit = await preflight(config);
  const baseline = await loadBaseline(config);
  const results: PromptResult[] = [];
  for (const spec of PROMPTS) {
    results.push(await postGenerate(config, spec));
  }

  const baselineRows = PROMPTS.map((spec) => baseline[spec.prompt] ?? spec.baseline);
  const p95Latency = percentile(results.map((result) => result.latencyMs), 95);
  const baselineP95Latency = percentile(baselineRows.map((row) => row.latencyMs), 95);
  const averageDensity = results.reduce((sum, result) => sum + result.count, 0) / Math.max(1, results.length);
  const baselineAverageDensity = baselineRows.reduce((sum, row) => sum + row.density, 0) / Math.max(1, baselineRows.length);
  const averageTrust = results.reduce((sum, result) => sum + result.trustScore, 0) / Math.max(1, results.length);
  const baselineAverageTrust = baselineRows.reduce((sum, row) => sum + row.trustScore, 0) / Math.max(1, baselineRows.length);
  const fallbackCount = results.filter((result) => result.fallbackUsed).length;
  const semanticDriftCount = results.filter((result) => result.semanticDrift).length;
  const latencyRegression = p95Latency > baselineP95Latency || results.some((result) => result.latencyMs > 30_000 || result.unaccountedLatency > 0 || result.missingTimeline);
  const densityRegression = averageDensity < baselineAverageDensity || results.some((result) => result.count < (baseline[result.prompt]?.density ?? 0));
  const qualityRegression = averageTrust < baselineAverageTrust || results.some((result) => result.trustScore < (baseline[result.prompt]?.trustScore ?? 0));
  const fallbackRegression = fallbackCount > 0;
  const driftRegression = semanticDriftCount > 0;
  const decision = latencyRegression || densityRegression || qualityRegression || fallbackRegression || driftRegression ? "FAIL" : "PASS";
  const reason = decision === "PASS"
    ? "No gym trust, density, fallback, semantic drift, or p95 latency regression detected."
    : [
        latencyRegression ? "latency regression" : null,
        qualityRegression ? "quality regression" : null,
        densityRegression ? "density regression" : null,
        fallbackRegression ? "fallback regression" : null,
        driftRegression ? "semantic drift" : null,
      ].filter(Boolean).join(", ");

  const report = {
    generatedAt: new Date().toISOString(),
    deployedCommit,
    baselineP95Latency,
    p95Latency,
    baselineAverageDensity,
    averageDensity,
    baselineAverageTrust,
    averageTrust,
    latency_regression: latencyRegression,
    quality_regression: qualityRegression,
    density_regression: densityRegression,
    fallback_regression: fallbackRegression,
    decision,
    reason,
    candidate_pool_health: results.map((result) => result.candidateHealth),
    semantic_drift: results.map((result) => ({
      prompt: result.prompt,
      ...result.drift,
    })),
    fast_path_isolation: {
      isolated: results.every((result) => !result.fallbackUsed && result.latencyMs <= 30_000 && !result.missingTimeline),
      dependency_leaks: results
        .flatMap((result) => [
          result.fallbackUsed ? `${result.prompt}:fallback` : null,
          result.missingTimeline ? `${result.prompt}:missing_timeline` : null,
          result.unaccountedLatency > 0 ? `${result.prompt}:unaccounted_latency` : null,
        ])
        .filter((value): value is string => !!value),
      worst_case_latency: Math.max(...results.map((result) => result.latencyMs)),
      pass: results.every((result) => !result.fallbackUsed && result.latencyMs <= 30_000 && !result.missingTimeline && result.unaccountedLatency === 0),
    },
    tradeoff_enforcer: {
      density_change: averageDensity >= baselineAverageDensity ? "+" : "-",
      trust_change: averageTrust >= baselineAverageTrust ? "+" : "-",
      latency_change: p95Latency <= baselineP95Latency ? "+" : "-",
      decision: decision === "PASS" ? "KEEP" : "REVERT",
    },
    prompts: results,
  };

  await mkdir(config.outDir, { recursive: true });
  await writeFile(path.join(config.outDir, "regression-guard-report.json"), `${JSON.stringify(report, null, 2)}\n`);
  process.stdout.write(`${JSON.stringify({
    latency_regression: latencyRegression,
    quality_regression: qualityRegression,
    density_regression: densityRegression,
    fallback_regression: fallbackRegression,
    decision,
    reason,
  }, null, 2)}\n`);
  if (decision === "FAIL") process.exit(1);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
