import type { HumanSceneConcept } from "./types";

/** Large reusable catalogue of human situations. Prefer phrases + relations over keyword spam. */
export const HUMAN_SCENE_CONCEPTS: HumanSceneConcept[] = [
  // ── Celebration / events ───────────────────────────────────────────────────
  {
    id: "festival",
    label: "Festival",
    family: "celebration",
    emotionalDirection: "communal lift",
    expectedEnergy: "high",
    energy: 0.78, valence: 0.72, tension: 0.28, intimacy: 0.15, optimism: 0.7,
    socialContext: "crowd", timeContext: "any", phase: "peak",
    musicalBehaviour: "peak_dance",
    cues: ["music festival", "festival field", "festival weekend", "festival day"],
  },
  {
    id: "rave",
    label: "Rave",
    family: "celebration",
    emotionalDirection: "ecstatic release",
    expectedEnergy: "high",
    energy: 0.88, valence: 0.65, tension: 0.35, intimacy: 0.1, optimism: 0.55,
    socialContext: "crowd", timeContext: "late_night", phase: "peak",
    musicalBehaviour: "peak_dance",
    cues: ["at a rave", "rave night", "warehouse rave", "on the rave"],
    cuePatterns: [/\b(?:at|during|going to|heading to)\s+(?:a\s+)?rave\b/i],
  },
  {
    id: "rave_comedown",
    label: "Rave comedown",
    family: "aftermath",
    emotionalDirection: "soft afterglow → flat",
    expectedEnergy: "low",
    energy: 0.28, valence: 0.42, tension: 0.18, intimacy: 0.45, optimism: 0.35,
    socialContext: "alone", timeContext: "dawn", phase: "aftermath",
    musicalBehaviour: "soft_electronic",
    cues: [
      "rave comedown", "comedown after the rave", "post rave", "post-rave",
      "after the rave", "after a rave", "rave hangover", "bus home after rave",
      "rave comedown bus", "afterparty comedown", "4am comedown",
    ],
    cuePatterns: [
      /\b(?:rave|club|festival)\s+comedown\b/i,
      /\bcomedown\b.*\b(?:rave|club|party|festival)\b/i,
      /\bafter\s+(?:the\s+|a\s+)?(?:rave|club night|warehouse)\b/i,
      /\bpost[-\s]?rave\b/i,
    ],
  },
  {
    id: "after_party",
    label: "After party",
    family: "aftermath",
    emotionalDirection: "tired euphoria",
    expectedEnergy: "low",
    energy: 0.34, valence: 0.55, tension: 0.12, intimacy: 0.5, optimism: 0.45,
    socialContext: "friends", timeContext: "dawn", phase: "aftermath",
    musicalBehaviour: "soft_electronic",
    cues: ["after party", "afterparty", "after the party", "kitchen after the club"],
  },
  {
    id: "wedding",
    label: "Wedding",
    family: "celebration",
    emotionalDirection: "ceremonial warmth → celebration",
    expectedEnergy: "medium",
    energy: 0.55, valence: 0.78, tension: 0.15, intimacy: 0.55, optimism: 0.8,
    socialContext: "family", timeContext: "any", phase: "peak",
    musicalBehaviour: "celebratory",
    cues: ["wedding", "wedding reception", "getting married"],
  },
  {
    id: "birthday_party",
    label: "Birthday party",
    family: "celebration",
    emotionalDirection: "social joy",
    expectedEnergy: "high",
    energy: 0.72, valence: 0.75, tension: 0.18, intimacy: 0.35, optimism: 0.7,
    socialContext: "friends", timeContext: "evening", phase: "peak",
    musicalBehaviour: "celebratory",
    cues: ["birthday party", "birthday night", "my birthday"],
  },
  {
    id: "house_party",
    label: "House party",
    family: "celebration",
    emotionalDirection: "casual social lift",
    expectedEnergy: "high",
    energy: 0.74, valence: 0.7, tension: 0.2, intimacy: 0.3, optimism: 0.65,
    socialContext: "friends", timeContext: "evening", phase: "peak",
    musicalBehaviour: "peak_dance",
    cues: ["house party", "houseparty", "party at mine", "party at theirs"],
  },

  // ── Travel / return ────────────────────────────────────────────────────────
  {
    id: "holiday_vacation",
    label: "Holiday (vacation)",
    family: "travel",
    emotionalDirection: "open freedom",
    expectedEnergy: "medium",
    energy: 0.52, valence: 0.68, tension: 0.12, intimacy: 0.35, optimism: 0.7,
    socialContext: "partner", timeContext: "any", phase: "steady",
    musicalBehaviour: "warm_acoustic",
    cues: ["on holiday", "summer holiday", "going on holiday", "holiday abroad", "vacation"],
  },
  {
    id: "after_holiday",
    label: "After holiday / back from vacation",
    family: "travel",
    emotionalDirection: "soft landing into ordinary life",
    expectedEnergy: "low",
    energy: 0.32, valence: 0.45, tension: 0.2, intimacy: 0.4, optimism: 0.35,
    socialContext: "alone", timeContext: "any", phase: "aftermath",
    musicalBehaviour: "reflective_indie",
    cues: [
      "after holiday", "after the holiday", "after a holiday", "day after a holiday",
      "holiday ends", "holiday is over", "holiday ended", "back from holiday",
      "back from vacation", "post holiday", "post-holiday", "holiday blues",
      "back home after holiday", "returning after holiday",
    ],
    cuePatterns: [
      /\b(?:day\s+)?after\s+(?:a\s+|the\s+)?holiday\b/i,
      /\bholiday\s+(?:ends|ended|is\s+over|over)\b/i,
      /\bback\s+(?:home\s+)?(?:from|after)\s+(?:a\s+|the\s+)?(?:holiday|vacation)\b/i,
      /\b(?:post[-\s]?holiday|holiday\s+blues)\b/i,
    ],
  },
  {
    id: "returning_home",
    label: "Returning home",
    family: "travel",
    emotionalDirection: "relief + mild flatness",
    expectedEnergy: "low",
    energy: 0.36, valence: 0.5, tension: 0.15, intimacy: 0.55, optimism: 0.45,
    socialContext: "alone", timeContext: "evening", phase: "recovery",
    musicalBehaviour: "nostalgic_warm",
    cues: ["returning home", "coming home", "back home", "headed home", "on the way home"],
  },
  {
    id: "airport",
    label: "Airport",
    family: "travel",
    emotionalDirection: "suspended transit",
    expectedEnergy: "low",
    energy: 0.35, valence: 0.4, tension: 0.35, intimacy: 0.25, optimism: 0.4,
    socialContext: "public", timeContext: "any", phase: "build_up",
    musicalBehaviour: "gentle_ambient",
    cues: ["at the airport", "airport lounge", "waiting at the airport", "airport morning"],
  },
  {
    id: "train_journey",
    label: "Train journey",
    family: "travel",
    emotionalDirection: "moving reflection",
    expectedEnergy: "low",
    energy: 0.34, valence: 0.48, tension: 0.18, intimacy: 0.4, optimism: 0.45,
    socialContext: "alone", timeContext: "any", phase: "steady",
    musicalBehaviour: "reflective_indie",
    cues: ["train journey", "on the train", "train window", "long train ride"],
  },
  {
    id: "late_night_bus",
    label: "Late-night bus",
    family: "travel",
    emotionalDirection: "tired motion",
    expectedEnergy: "low",
    energy: 0.26, valence: 0.38, tension: 0.22, intimacy: 0.35, optimism: 0.3,
    socialContext: "alone", timeContext: "late_night", phase: "aftermath",
    musicalBehaviour: "soft_electronic",
    cues: ["late night bus", "night bus home", "bus home", "last bus home", "comedown bus"],
  },
  {
    id: "driving",
    label: "Driving",
    family: "motion",
    emotionalDirection: "forward motion",
    expectedEnergy: "medium",
    energy: 0.55, valence: 0.55, tension: 0.2, intimacy: 0.3, optimism: 0.55,
    socialContext: "alone", timeContext: "any", phase: "steady",
    musicalBehaviour: "motion_pulse",
    // Prefer multi-word phrases — bare "driving" collides with drive→driving normalisation.
    cues: ["night drive", "road trip", "motorway drive", "long drive", "highway drive", "windows down drive"],
  },
  {
    id: "walking",
    label: "Walking",
    family: "motion",
    emotionalDirection: "body-led thinking",
    expectedEnergy: "low",
    energy: 0.38, valence: 0.45, tension: 0.2, intimacy: 0.45, optimism: 0.4,
    socialContext: "alone", timeContext: "any", phase: "reflection",
    musicalBehaviour: "reflective_indie",
    cues: ["walking home", "long walk", "walking at night", "evening walk"],
  },

  // ── Work / achievement / failure ───────────────────────────────────────────
  {
    id: "new_job",
    label: "New job",
    family: "work",
    emotionalDirection: "nervous optimism",
    expectedEnergy: "medium",
    energy: 0.55, valence: 0.62, tension: 0.35, intimacy: 0.25, optimism: 0.7,
    socialContext: "public", timeContext: "morning", phase: "build_up",
    musicalBehaviour: "steady_focus",
    cues: ["first day at work", "new job", "starting a new job", "first day new job"],
  },
  {
    id: "lost_job",
    label: "Lost job",
    family: "work",
    emotionalDirection: "deflation",
    expectedEnergy: "low",
    energy: 0.28, valence: 0.28, tension: 0.4, intimacy: 0.45, optimism: 0.2,
    socialContext: "alone", timeContext: "any", phase: "aftermath",
    musicalBehaviour: "melancholic_ballad",
    cues: ["lost my job", "got fired", "made redundant", "laid off", "lost the job"],
  },
  {
    id: "interview",
    label: "Interview",
    family: "work",
    emotionalDirection: "tense concentration",
    expectedEnergy: "medium",
    energy: 0.48, valence: 0.4, tension: 0.55, intimacy: 0.2, optimism: 0.45,
    socialContext: "public", timeContext: "any", phase: "build_up",
    musicalBehaviour: "tense_hold",
    cues: ["job interview", "before an interview", "interview nerves"],
  },
  {
    id: "failed_interview",
    label: "Failed interview",
    family: "failure",
    emotionalDirection: "quiet deflation",
    expectedEnergy: "low",
    energy: 0.28, valence: 0.28, tension: 0.35, intimacy: 0.5, optimism: 0.2,
    socialContext: "alone", timeContext: "any", phase: "aftermath",
    musicalBehaviour: "melancholic_ballad",
    cues: [
      "failing a job interview", "failed a job interview", "after failing an interview",
      "walking home after failing", "didn't get the job",
    ],
    cuePatterns: [
      /\bafter\s+fail(?:ed|ing)?\s+(?:a\s+)?(?:job\s+)?interview\b/i,
      /\bfail(?:ed|ing)?\s+(?:a\s+)?(?:job\s+)?interview\b/i,
      /\bdidn'?t\s+get\s+(?:the\s+)?(?:job|role|position)\b/i,
    ],
  },
  {
    id: "promotion",
    label: "Promotion",
    family: "achievement",
    emotionalDirection: "quiet pride",
    expectedEnergy: "medium",
    energy: 0.58, valence: 0.72, tension: 0.15, intimacy: 0.35, optimism: 0.75,
    socialContext: "alone", timeContext: "any", phase: "peak",
    musicalBehaviour: "celebratory",
    cues: ["got promoted", "promotion", "new title at work"],
  },
  {
    id: "graduation",
    label: "Graduation",
    family: "achievement",
    emotionalDirection: "bittersweet pride",
    expectedEnergy: "medium",
    energy: 0.55, valence: 0.68, tension: 0.2, intimacy: 0.45, optimism: 0.7,
    socialContext: "family", timeContext: "any", phase: "peak",
    musicalBehaviour: "nostalgic_warm",
    cues: ["graduation", "graduating", "graduation day", "left university", "leaving uni"],
  },
  {
    id: "retirement",
    label: "Retirement",
    family: "life_change",
    emotionalDirection: "open stillness",
    expectedEnergy: "low",
    energy: 0.32, valence: 0.55, tension: 0.15, intimacy: 0.5, optimism: 0.55,
    socialContext: "partner", timeContext: "any", phase: "reflection",
    musicalBehaviour: "warm_acoustic",
    cues: ["retirement", "first day of retirement", "just retired"],
  },

  // ── Health / waiting ───────────────────────────────────────────────────────
  {
    id: "hospital",
    label: "Hospital",
    family: "health",
    emotionalDirection: "sterile tension",
    expectedEnergy: "low",
    energy: 0.3, valence: 0.32, tension: 0.55, intimacy: 0.35, optimism: 0.3,
    socialContext: "public", timeContext: "any", phase: "build_up",
    musicalBehaviour: "tense_hold",
    cues: ["in hospital", "at the hospital", "hospital room", "hospital visit"],
  },
  {
    id: "waiting_room",
    label: "Waiting room / awaiting results",
    family: "waiting",
    emotionalDirection: "suspended dread",
    expectedEnergy: "low",
    energy: 0.3, valence: 0.35, tension: 0.55, intimacy: 0.4, optimism: 0.35,
    socialContext: "public", timeContext: "any", phase: "build_up",
    musicalBehaviour: "tense_hold",
    cues: [
      "waiting room", "waiting for test results", "nervously waiting",
      "waiting to hear", "doctors waiting", "at the doctors waiting",
    ],
    cuePatterns: [
      /\bwaiting\s+(?:for|on)\s+(?:the\s+|my\s+)?(?:test\s+|exam\s+)?results?\b/i,
      /\bnervously\s+waiting\b/i,
      /\bwaiting\s+room\b/i,
    ],
  },
  {
    id: "relief_after_results",
    label: "Relief after results",
    family: "relief",
    emotionalDirection: "release of held breath",
    expectedEnergy: "low",
    energy: 0.38, valence: 0.65, tension: 0.1, intimacy: 0.55, optimism: 0.7,
    socialContext: "alone", timeContext: "any", phase: "recovery",
    musicalBehaviour: "healing",
    cues: ["good news from the doctor", "all clear", "results came back fine", "sigh of relief"],
  },

  // ── Relationships ──────────────────────────────────────────────────────────
  {
    id: "breakup",
    label: "Breakup",
    family: "relationship",
    emotionalDirection: "grief + empty space",
    expectedEnergy: "low",
    energy: 0.28, valence: 0.25, tension: 0.4, intimacy: 0.7, optimism: 0.2,
    socialContext: "alone", timeContext: "late_night", phase: "aftermath",
    musicalBehaviour: "melancholic_ballad",
    cues: ["breakup", "break up", "just broke up", "after the breakup", "she left", "he left"],
  },
  {
    id: "divorce",
    label: "Divorce",
    family: "relationship",
    emotionalDirection: "heavy ending",
    expectedEnergy: "low",
    energy: 0.26, valence: 0.28, tension: 0.4, intimacy: 0.55, optimism: 0.25,
    socialContext: "alone", timeContext: "any", phase: "aftermath",
    musicalBehaviour: "melancholic_ballad",
    cues: ["divorce", "getting divorced", "after the divorce"],
  },
  {
    id: "new_relationship",
    label: "New relationship",
    family: "relationship",
    emotionalDirection: "tender lift",
    expectedEnergy: "medium",
    energy: 0.52, valence: 0.72, tension: 0.2, intimacy: 0.75, optimism: 0.75,
    socialContext: "partner", timeContext: "evening", phase: "build_up",
    musicalBehaviour: "intimate",
    cues: ["new relationship", "just started dating", "falling for someone", "new love"],
  },
  {
    id: "long_distance",
    label: "Long-distance relationship",
    family: "relationship",
    emotionalDirection: "missing + hope",
    expectedEnergy: "low",
    energy: 0.34, valence: 0.42, tension: 0.3, intimacy: 0.8, optimism: 0.45,
    socialContext: "alone", timeContext: "late_night", phase: "reflection",
    musicalBehaviour: "intimate",
    cues: ["long distance", "long-distance", "missing them", "miles apart"],
  },
  {
    id: "missing_someone",
    label: "Missing someone",
    family: "relationship",
    emotionalDirection: "yearning",
    expectedEnergy: "low",
    energy: 0.3, valence: 0.35, tension: 0.28, intimacy: 0.75, optimism: 0.35,
    socialContext: "alone", timeContext: "late_night", phase: "reflection",
    musicalBehaviour: "intimate",
    cues: ["missing someone", "miss you", "thinking of you", "wish you were here"],
  },
  {
    id: "old_friendship",
    label: "Old friendship / reunion",
    family: "relationship",
    emotionalDirection: "warm nostalgia",
    expectedEnergy: "medium",
    energy: 0.48, valence: 0.65, tension: 0.12, intimacy: 0.6, optimism: 0.6,
    socialContext: "friends", timeContext: "evening", phase: "reflection",
    musicalBehaviour: "nostalgic_warm",
    cues: ["old friends", "reunited with friends", "catching up with old friends", "friendship reunion"],
  },
  {
    id: "family_gathering",
    label: "Family gathering",
    family: "family",
    emotionalDirection: "warm / complicated togetherness",
    expectedEnergy: "medium",
    energy: 0.45, valence: 0.55, tension: 0.25, intimacy: 0.55, optimism: 0.5,
    socialContext: "family", timeContext: "evening", phase: "steady",
    musicalBehaviour: "warm_acoustic",
    cues: ["family gathering", "family dinner", "sunday family", "seeing the family"],
  },

  // ── Life milestones / home ─────────────────────────────────────────────────
  {
    id: "first_apartment",
    label: "First apartment",
    family: "home",
    emotionalDirection: "quiet independence",
    expectedEnergy: "low",
    energy: 0.4, valence: 0.62, tension: 0.2, intimacy: 0.55, optimism: 0.7,
    socialContext: "alone", timeContext: "evening", phase: "build_up",
    musicalBehaviour: "warm_acoustic",
    cues: ["first apartment", "first flat", "moved into my first place", "keys to my own place"],
  },
  {
    id: "moving_house",
    label: "Moving house",
    family: "home",
    emotionalDirection: "rupture + possibility",
    expectedEnergy: "medium",
    energy: 0.5, valence: 0.48, tension: 0.4, intimacy: 0.35, optimism: 0.5,
    socialContext: "alone", timeContext: "any", phase: "build_up",
    musicalBehaviour: "reflective_indie",
    cues: ["moving house", "moving flat", "packing up", "packing boxes", "unpacking boxes"],
  },
  {
    id: "leaving_home",
    label: "Leaving home",
    family: "home",
    emotionalDirection: "bittersweet threshold",
    expectedEnergy: "low",
    energy: 0.38, valence: 0.45, tension: 0.3, intimacy: 0.55, optimism: 0.5,
    socialContext: "alone", timeContext: "any", phase: "build_up",
    musicalBehaviour: "nostalgic_warm",
    cues: ["leaving home", "left home", "moving out of my parents", "first time leaving home"],
  },
  {
    id: "leaving_school",
    label: "Leaving school / university",
    family: "life_change",
    emotionalDirection: "ending chapter",
    expectedEnergy: "medium",
    energy: 0.45, valence: 0.5, tension: 0.25, intimacy: 0.45, optimism: 0.55,
    socialContext: "friends", timeContext: "any", phase: "reflection",
    musicalBehaviour: "nostalgic_warm",
    cues: ["leaving school", "left school", "end of uni", "leaving university", "finished uni"],
  },
  {
    id: "fresh_start",
    label: "Fresh start",
    family: "life_change",
    emotionalDirection: "quiet courage",
    expectedEnergy: "medium",
    energy: 0.5, valence: 0.62, tension: 0.25, intimacy: 0.4, optimism: 0.75,
    socialContext: "alone", timeContext: "morning", phase: "build_up",
    musicalBehaviour: "healing",
    cues: ["fresh start", "new chapter", "starting over", "turning over a new leaf"],
  },

  // ── Emotional states / healing ─────────────────────────────────────────────
  {
    id: "grief",
    label: "Grief",
    family: "emotion",
    emotionalDirection: "heavy presence",
    expectedEnergy: "low",
    energy: 0.22, valence: 0.2, tension: 0.35, intimacy: 0.7, optimism: 0.15,
    socialContext: "alone", timeContext: "any", phase: "aftermath",
    musicalBehaviour: "melancholic_ballad",
    cues: ["grief", "grieving", "mourning", "lost someone"],
  },
  {
    id: "funeral",
    label: "Funeral",
    family: "life_event",
    emotionalDirection: "solemn remembrance",
    expectedEnergy: "low",
    energy: 0.2, valence: 0.25, tension: 0.3, intimacy: 0.65, optimism: 0.2,
    socialContext: "family", timeContext: "any", phase: "reflection",
    musicalBehaviour: "gentle_ambient",
    cues: ["funeral", "memorial", "wake"],
  },
  {
    id: "birth",
    label: "Birth / new baby",
    family: "life_event",
    emotionalDirection: "tender awe",
    expectedEnergy: "low",
    energy: 0.35, valence: 0.7, tension: 0.2, intimacy: 0.85, optimism: 0.8,
    socialContext: "partner", timeContext: "any", phase: "peak",
    musicalBehaviour: "intimate",
    cues: ["new baby", "just gave birth", "bringing baby home", "newborn"],
  },
  {
    id: "burnout",
    label: "Burnout",
    family: "emotion",
    emotionalDirection: "depleted",
    expectedEnergy: "low",
    energy: 0.22, valence: 0.3, tension: 0.35, intimacy: 0.4, optimism: 0.2,
    socialContext: "alone", timeContext: "evening", phase: "aftermath",
    musicalBehaviour: "gentle_ambient",
    cues: ["burnout", "burnt out", "burned out", "completely drained"],
  },
  {
    id: "healing",
    label: "Healing / rebuilding",
    family: "emotion",
    emotionalDirection: "slow repair",
    expectedEnergy: "low",
    energy: 0.34, valence: 0.5, tension: 0.15, intimacy: 0.55, optimism: 0.55,
    socialContext: "alone", timeContext: "any", phase: "recovery",
    musicalBehaviour: "healing",
    cues: ["healing", "rebuilding", "getting better", "slowly recovering", "forgiveness"],
  },
  {
    id: "loneliness",
    label: "Loneliness",
    family: "emotion",
    emotionalDirection: "empty space",
    expectedEnergy: "low",
    energy: 0.28, valence: 0.3, tension: 0.3, intimacy: 0.65, optimism: 0.25,
    socialContext: "alone", timeContext: "late_night", phase: "reflection",
    musicalBehaviour: "melancholic_ballad",
    cues: ["lonely", "loneliness", "feeling alone", "nobody around"],
  },
  {
    id: "homesickness",
    label: "Homesickness",
    family: "emotion",
    emotionalDirection: "yearning for place",
    expectedEnergy: "low",
    energy: 0.3, valence: 0.35, tension: 0.25, intimacy: 0.6, optimism: 0.35,
    socialContext: "alone", timeContext: "evening", phase: "reflection",
    musicalBehaviour: "nostalgic_warm",
    cues: ["homesick", "homesickness", "miss home", "missing home"],
  },
  {
    id: "hope",
    label: "Hope",
    family: "emotion",
    emotionalDirection: "soft forward lean",
    expectedEnergy: "medium",
    energy: 0.45, valence: 0.65, tension: 0.15, intimacy: 0.45, optimism: 0.8,
    socialContext: "alone", timeContext: "morning", phase: "build_up",
    musicalBehaviour: "healing",
    cues: ["feeling hopeful", "hope again", "things getting better"],
  },
  {
    id: "acceptance",
    label: "Acceptance",
    family: "emotion",
    emotionalDirection: "settled stillness",
    expectedEnergy: "low",
    energy: 0.32, valence: 0.48, tension: 0.1, intimacy: 0.5, optimism: 0.5,
    socialContext: "alone", timeContext: "any", phase: "reflection",
    musicalBehaviour: "gentle_ambient",
    cues: ["acceptance", "coming to terms", "letting go", "peace with it"],
  },
  {
    id: "quiet_confidence",
    label: "Quiet confidence",
    family: "emotion",
    emotionalDirection: "steady self-possession",
    expectedEnergy: "medium",
    energy: 0.5, valence: 0.62, tension: 0.1, intimacy: 0.4, optimism: 0.7,
    socialContext: "alone", timeContext: "any", phase: "steady",
    musicalBehaviour: "steady_focus",
    cues: ["quiet confidence", "feeling capable", "in my own skin"],
  },
  {
    id: "personal_growth",
    label: "Personal growth",
    family: "emotion",
    emotionalDirection: "earned clarity",
    expectedEnergy: "medium",
    energy: 0.48, valence: 0.6, tension: 0.15, intimacy: 0.45, optimism: 0.7,
    socialContext: "alone", timeContext: "any", phase: "reflection",
    musicalBehaviour: "reflective_indie",
    cues: ["personal growth", "becoming myself", "growing as a person"],
  },
  {
    id: "creative_flow",
    label: "Creative flow",
    family: "focus",
    emotionalDirection: "immersed forward",
    expectedEnergy: "medium",
    energy: 0.52, valence: 0.58, tension: 0.2, intimacy: 0.35, optimism: 0.65,
    socialContext: "alone", timeContext: "any", phase: "peak",
    musicalBehaviour: "steady_focus",
    cues: ["creative flow", "in the zone writing", "making something", "studio session"],
  },
  {
    id: "writers_block",
    label: "Writer's block",
    family: "focus",
    emotionalDirection: "stuck friction",
    expectedEnergy: "low",
    energy: 0.32, valence: 0.35, tension: 0.4, intimacy: 0.4, optimism: 0.3,
    socialContext: "alone", timeContext: "any", phase: "steady",
    musicalBehaviour: "gentle_ambient",
    cues: ["writer's block", "writers block", "can't write", "stuck creatively"],
  },
  {
    id: "freedom",
    label: "Freedom",
    family: "emotion",
    emotionalDirection: "open air",
    expectedEnergy: "medium",
    energy: 0.58, valence: 0.7, tension: 0.1, intimacy: 0.3, optimism: 0.75,
    socialContext: "alone", timeContext: "any", phase: "peak",
    musicalBehaviour: "warm_acoustic",
    cues: ["feeling free", "freedom", "no obligations", "wide open day"],
  },
  {
    id: "adventure",
    label: "Adventure",
    family: "emotion",
    emotionalDirection: "curious forward",
    expectedEnergy: "high",
    energy: 0.7, valence: 0.7, tension: 0.3, intimacy: 0.25, optimism: 0.75,
    socialContext: "friends", timeContext: "any", phase: "peak",
    musicalBehaviour: "high_drive",
    cues: ["adventure", "exploring somewhere new", "road adventure"],
  },
  {
    id: "reflection",
    label: "Reflection",
    family: "emotion",
    emotionalDirection: "inward slow",
    expectedEnergy: "low",
    energy: 0.3, valence: 0.42, tension: 0.2, intimacy: 0.6, optimism: 0.4,
    socialContext: "alone", timeContext: "evening", phase: "reflection",
    musicalBehaviour: "reflective_indie",
    cues: ["reflecting", "looking back", "thinking about life", "sunday reflection"],
  },

  // ── Exercise ───────────────────────────────────────────────────────────────
  {
    id: "gym_peak",
    label: "Gym peak effort",
    family: "exercise",
    emotionalDirection: "forceful push",
    expectedEnergy: "high",
    energy: 0.88, valence: 0.55, tension: 0.45, intimacy: 0.1, optimism: 0.55,
    socialContext: "alone", timeContext: "any", phase: "peak",
    musicalBehaviour: "high_drive",
    cues: ["heavy lifting", "gym pump", "max effort", "pr day", "aggressive workout"],
  },
  {
    id: "gym_cooldown",
    label: "Gym cool-down / recovery",
    family: "exercise",
    emotionalDirection: "spent release",
    expectedEnergy: "low",
    energy: 0.35, valence: 0.55, tension: 0.1, intimacy: 0.3, optimism: 0.55,
    socialContext: "alone", timeContext: "any", phase: "recovery",
    musicalBehaviour: "soft_electronic",
    cues: ["cool down after gym", "post workout stretch", "gym recovery", "after the gym"],
  },
  {
    id: "competition",
    label: "Competition",
    family: "exercise",
    emotionalDirection: "focused edge",
    expectedEnergy: "high",
    energy: 0.8, valence: 0.55, tension: 0.5, intimacy: 0.15, optimism: 0.55,
    socialContext: "crowd", timeContext: "any", phase: "peak",
    musicalBehaviour: "high_drive",
    cues: ["match day", "game day", "competition", "before the race"],
  },

  // ── Time / weather / atmosphere ────────────────────────────────────────────
  {
    id: "summer_evening",
    label: "Summer evening",
    family: "atmosphere",
    emotionalDirection: "warm open",
    expectedEnergy: "medium",
    energy: 0.48, valence: 0.68, tension: 0.1, intimacy: 0.45, optimism: 0.65,
    socialContext: "friends", timeContext: "evening", phase: "steady",
    musicalBehaviour: "warm_acoustic",
    cues: ["summer evening", "warm evening", "golden hour summer"],
    cuePatterns: [/\beuphoric\s+summer\s+evening\b/i],
  },
  {
    id: "sunday_evening",
    label: "Sunday evening",
    family: "atmosphere",
    emotionalDirection: "soft melancholy before week",
    expectedEnergy: "low",
    energy: 0.32, valence: 0.42, tension: 0.25, intimacy: 0.5, optimism: 0.35,
    socialContext: "alone", timeContext: "evening", phase: "reflection",
    musicalBehaviour: "reflective_indie",
    cues: ["sunday evening", "sunday scaries", "sunday night"],
  },
  {
    id: "monday_morning",
    label: "Monday morning",
    family: "atmosphere",
    emotionalDirection: "reluctant start",
    expectedEnergy: "medium",
    energy: 0.45, valence: 0.4, tension: 0.35, intimacy: 0.25, optimism: 0.4,
    socialContext: "alone", timeContext: "morning", phase: "build_up",
    musicalBehaviour: "steady_focus",
    cues: ["monday morning", "monday commute", "start of the week"],
  },
  {
    id: "night_shift",
    label: "Night shift",
    family: "work",
    emotionalDirection: "altered hours grit",
    expectedEnergy: "medium",
    energy: 0.48, valence: 0.4, tension: 0.35, intimacy: 0.25, optimism: 0.35,
    socialContext: "alone", timeContext: "late_night", phase: "steady",
    musicalBehaviour: "soft_electronic",
    cues: ["night shift", "working nights", "3am at work"],
  },
  {
    id: "rain",
    label: "Rain",
    family: "atmosphere",
    emotionalDirection: "enclosed soft",
    expectedEnergy: "low",
    energy: 0.3, valence: 0.4, tension: 0.2, intimacy: 0.5, optimism: 0.35,
    socialContext: "alone", timeContext: "any", phase: "steady",
    musicalBehaviour: "reflective_indie",
    cues: ["in the rain", "rainy day", "walking in the rain", "rain on the window"],
  },
  {
    id: "snow",
    label: "Snow",
    family: "atmosphere",
    emotionalDirection: "hushed wonder",
    expectedEnergy: "low",
    energy: 0.28, valence: 0.5, tension: 0.1, intimacy: 0.5, optimism: 0.5,
    socialContext: "alone", timeContext: "any", phase: "steady",
    musicalBehaviour: "gentle_ambient",
    cues: ["snowing", "first snow", "snowy walk", "snow day"],
  },
  {
    id: "late_night_petrol",
    label: "Late-night petrol station",
    family: "atmosphere",
    emotionalDirection: "liminal alone",
    expectedEnergy: "low",
    energy: 0.25, valence: 0.35, tension: 0.35, intimacy: 0.45, optimism: 0.3,
    socialContext: "alone", timeContext: "late_night", phase: "reflection",
    musicalBehaviour: "soft_electronic",
    cues: ["petrol station at night", "2am petrol", "gas station late night", "forecourt at night"],
  },
  {
    id: "christmas_holiday",
    label: "Christmas holiday",
    family: "celebration",
    emotionalDirection: "festive warmth / nostalgia",
    expectedEnergy: "medium",
    energy: 0.48, valence: 0.7, tension: 0.1, intimacy: 0.55, optimism: 0.65,
    socialContext: "family", timeContext: "evening", phase: "peak",
    musicalBehaviour: "celebratory",
    cues: [
      "christmas", "xmas", "christmas eve", "christmas morning", "christmas holiday",
      "festive season", "holiday song", "holiday classics",
    ],
  },
  {
    id: "quiet_revision",
    label: "Quiet revision / study",
    family: "focus",
    emotionalDirection: "still concentration",
    expectedEnergy: "low",
    energy: 0.28, valence: 0.45, tension: 0.2, intimacy: 0.4, optimism: 0.45,
    socialContext: "alone", timeContext: "morning", phase: "steady",
    musicalBehaviour: "steady_focus",
    cues: ["quiet revision", "morning revision", "studying quietly", "exam revision"],
  },

  // ── Product-demo scene prototypes (Human Curator Reality Audit ROI) ────────
  {
    id: "boss_fight",
    label: "Boss fight",
    family: "gaming",
    emotionalDirection: "combat surge → resolve",
    expectedEnergy: "high",
    energy: 0.88, valence: 0.42, tension: 0.78, intimacy: 0.1, optimism: 0.45,
    socialContext: "alone", timeContext: "any", phase: "peak",
    musicalBehaviour: "high_drive",
    cues: [
      "boss fight", "boss battle", "final boss", "gaming boss", "raid boss",
      "fighting the boss", "boss music",
    ],
    cuePatterns: [
      /\bboss\s+(?:fight|battle|music)\b/i,
      /\bfinal\s+boss\b/i,
    ],
  },
  {
    id: "neon_drive",
    label: "Neon / tek night drive",
    family: "travel",
    emotionalDirection: "chrome pulse through night city",
    expectedEnergy: "high",
    energy: 0.72, valence: 0.45, tension: 0.48, intimacy: 0.2, optimism: 0.4,
    socialContext: "alone", timeContext: "late_night", phase: "steady",
    musicalBehaviour: "motion_pulse",
    cues: [
      "neon drive", "neon streets", "synthwave drive", "cyberpunk drive",
      "retrowave night", "tek drive", "hard techno drive", "neon tek",
    ],
    cuePatterns: [
      /\bneon\s+(?:drive|city|streets?|nights?|tek|techno|synth)\b/i,
      /\b(?:synthwave|retrowave|cyberpunk)\b/i,
      /\bhard\s+techno\b/i,
    ],
  },
  {
    id: "goth_night",
    label: "Goth / darkwave night",
    family: "atmosphere",
    emotionalDirection: "velvet black romance / ritual",
    expectedEnergy: "medium",
    energy: 0.48, valence: 0.28, tension: 0.55, intimacy: 0.45, optimism: 0.25,
    socialContext: "alone", timeContext: "late_night", phase: "steady",
    musicalBehaviour: "tense_hold",
    cues: [
      "goth night", "goth playlist", "gothic", "darkwave", "post-punk night",
      "industrial goth", "batcave", "goth club",
    ],
    cuePatterns: [
      /\bgoth(?:ic)?\b/i,
      /\bdarkwave\b/i,
      /\bpost[-\s]?punk\b/i,
    ],
  },
  {
    id: "grunge_session",
    label: "Grunge session",
    family: "atmosphere",
    emotionalDirection: "raw Seattle weight",
    expectedEnergy: "high",
    energy: 0.68, valence: 0.32, tension: 0.55, intimacy: 0.25, optimism: 0.3,
    socialContext: "alone", timeContext: "any", phase: "peak",
    musicalBehaviour: "high_drive",
    cues: ["grunge", "seattle grunge", "seattle sound", "90s grunge", "grunge night"],
    cuePatterns: [/\bgrunge\b/i, /\bseattle\s+(?:sound|grunge)\b/i],
  },
  {
    id: "lofi_study",
    label: "Lo-fi study",
    family: "focus",
    emotionalDirection: "soft looped concentration",
    expectedEnergy: "low",
    energy: 0.32, valence: 0.48, tension: 0.12, intimacy: 0.55, optimism: 0.45,
    socialContext: "alone", timeContext: "any", phase: "steady",
    musicalBehaviour: "steady_focus",
    cues: [
      "lofi", "lo-fi", "lofi beats", "study beats", "chillhop", "lofi study",
      "lo-fi but", "homework beats",
    ],
    cuePatterns: [/\blo-?fi\b/i, /\bchillhop\b/i, /\bstudy\s+beats?\b/i],
  },
  {
    id: "quiet_rage",
    label: "Quiet rage",
    family: "emotion",
    emotionalDirection: "simmering anger held in",
    expectedEnergy: "medium",
    energy: 0.55, valence: 0.22, tension: 0.72, intimacy: 0.35, optimism: 0.2,
    socialContext: "alone", timeContext: "any", phase: "steady",
    musicalBehaviour: "tense_hold",
    cues: [
      "quiet rage", "simmering rage", "simmering anger", "repressed rage",
      "contained fury", "angry but quiet",
    ],
    cuePatterns: [
      /\bquiet\s+rage\b/i,
      /\bsimmer(?:ing)?\s+(?:rage|anger|fury)\b/i,
      /\brepressed\s+(?:rage|anger)\b/i,
    ],
  },
];
