import { kb } from "./types";

export const COUNTRY_REGION_ENTRIES = [
  kb("japan", "country", [/\bjapan(?:ese)?\b/i], "japan-atmosphere",
    ["urban", "nocturnal", "cinematic", "reflective"],
    ["japan", "neon", "urban", "transit"],
    ["electronic", "ambient", "indie", "jazz"],
    { themes: ["city", "transit"], places: ["city"], signalWeight: 0.35 }),
  kb("france", "country", [/\bfrance\b/i, /\bfrench\b/i], "france-atmosphere",
    ["romantic", "reflective", "nostalgia", "cozy"],
    ["france", "café", "countryside", "slow"],
    ["jazz", "chanson", "classical", "folk"],
    { themes: ["travel", "romance"], weather: ["rain"], signalWeight: 0.35 }),
  kb("italy", "country", [/\bitaly\b/i, /\bitalian\b/i], "italy-atmosphere",
    ["romantic", "nostalgia", "adventure", "cozy"],
    ["italy", "warm", "historic", "summer"],
    ["classical", "folk", "jazz", "ambient"],
    { places: ["city"], signalWeight: 0.35 }),
  kb("scandinavia", "region", [/\bscandinav(?:ia|ian)\b/i, /\bnordic\b/i, /\bsweden\b/i, /\bnorway\b/i, /\bdenmark\b/i, /\bfinland\b/i], "scandinavia-atmosphere",
    ["melancholy", "reflective", "lonely", "vintage"],
    ["scandinavia", "minimal", "cold", "introspective"],
    ["ambient", "electronic", "indie", "folk"],
    { weather: ["snow"], signalWeight: 0.35 }),
  kb("united-kingdom", "country", [/\b(?:united kingdom|britain|british|england|english|uk)\b/i], "uk-atmosphere",
    ["nostalgia", "melancholy", "vintage", "urban"],
    ["british", "rain", "pub", "history"],
    ["rock", "indie", "folk", "electronic"],
    { weather: ["rain"], signalWeight: 0.35 }),
  kb("united-states", "country", [/\b(?:united states|america|american|usa|u\.s\.)\b/i], "usa-atmosphere",
    ["adventure", "nostalgia", "reflective", "cinematic"],
    ["americana", "highway", "road-trip", "regional"],
    ["rock", "country", "hip_hop", "indie"],
    { places: ["highway"], themes: ["travel"], signalWeight: 0.35 }),
  kb("rural-france-drive", "location", [/\bdriving\b.*\b(?:rural\s+)?france\b/i, /\bfrance\b.*\b(?:countryside|rural|driving)\b/i], "france-atmosphere",
    ["romantic", "reflective", "nostalgia", "adventure"],
    ["france", "countryside", "vineyard", "slow"],
    ["chanson", "folk", "jazz", "classical"],
    { places: ["countryside"], atmosphereOverActivity: true }),
  kb("small-town-america-autumn", "location", [/\bsmall.?town\s+america\b/i, /\bamerica\b.*\bautumn\b/i, /\bautumn\b.*\b(?:small town|hometown)\b/i], "small-town-america",
    ["nostalgia", "melancholy", "cozy", "reflective"],
    ["americana", "small-town", "autumn", "hometown"],
    ["folk", "country", "indie", "rock"],
    { weather: ["rain"], atmosphereOverActivity: true }),
];

export const CITY_ENTRIES = [
  kb("tokyo", "city", [/\btokyo\b/i], "tokyo-night",
    ["nocturnal", "urban", "cinematic", "dreamlike"],
    ["tokyo", "neon", "urban", "transit"],
    ["electronic", "ambient", "indie", "jazz"],
    { places: ["city", "train"], times: ["night", "late-night"] }),
  kb("paris", "city", [/\bparis\b/i], "paris-cafe",
    ["romantic", "melancholy", "reflective", "vintage"],
    ["paris", "café", "french", "cobblestone"],
    ["jazz", "chanson", "classical", "indie"],
    { places: ["city", "café"] }),
  kb("london", "city", [/\blondon\b/i], "london-night",
    ["nocturnal", "urban", "melancholy", "vintage"],
    ["london", "rain", "fog", "history"],
    ["rock", "indie", "electronic", "jazz"],
    { places: ["city"], times: ["night", "midnight"], weather: ["rain", "fog"] }),
  kb("london-midnight-walk", "location", [/\bwalking\b.*\blondon\b/i, /\blondon\b.*\b(?:midnight|walking|walk)\b/i], "london-night",
    ["nocturnal", "lonely", "reflective", "cinematic"],
    ["london", "midnight", "street", "rain"],
    ["indie", "electronic", "jazz", "ambient"],
    { atmosphereOverActivity: true }),
  kb("berlin", "city", [/\bberlin\b/i], "berlin-warehouse",
    ["industrial", "nocturnal", "futuristic", "cinematic"],
    ["berlin", "warehouse", "techno", "underground"],
    ["electronic", "techno", "ambient", "industrial"],
    { places: ["warehouse", "city"] }),
  kb("berlin-warehouse-sunrise", "location", [/\bberlin\b.*\b(?:warehouse|sunrise|rave)\b/i], "berlin-warehouse",
    ["adventure", "industrial", "nocturnal", "cinematic"],
    ["berlin", "warehouse", "sunrise", "rave"],
    ["electronic", "techno", "ambient", "house"],
    { times: ["sunrise"], atmosphereOverActivity: true }),
  kb("new-york", "city", [/\bnew york\b/i, /\bnyc\b/i, /\bmanhattan\b/i], "new-york-city",
    ["urban", "cinematic", "nocturnal", "lonely"],
    ["new-york", "skyline", "urban", "energy"],
    ["hip_hop", "jazz", "electronic", "indie"],
    { places: ["city"] }),
  kb("los-angeles", "city", [/\blos angeles\b/i, /\bhollywood\b/i], "los-angeles",
    ["cinematic", "nostalgia", "urban", "dreamlike"],
    ["los-angeles", "highway", "sunset", "film"],
    ["rock", "hip_hop", "electronic", "indie"],
    { places: ["city", "highway"] }),
  kb("manchester", "city", [/\bmanchester\b/i], "manchester-night",
    ["urban", "nostalgia", "industrial", "reflective"],
    ["manchester", "rain", "industrial", "nightlife"],
    ["rock", "indie", "electronic", "hip_hop"],
    { places: ["city"] }),
  kb("chicago", "city", [/\bchicago\b/i], "chicago-blues",
    ["urban", "nocturnal", "melancholy", "vintage"],
    ["chicago", "blues", "windy", "lake"],
    ["blues", "jazz", "hip_hop", "soul"],
    { places: ["city"] }),
  kb("seoul", "city", [/\bseoul\b/i], "seoul-night",
    ["urban", "nocturnal", "cinematic", "futuristic"],
    ["seoul", "neon", "k-pop", "urban"],
    ["electronic", "pop", "hip_hop", "ambient"],
    { places: ["city"] }),
  kb("hong-kong", "city", [/\bhong kong\b/i], "hong-kong-night",
    ["urban", "nocturnal", "cinematic", "lonely"],
    ["hong-kong", "neon", "harbour", "dense"],
    ["electronic", "jazz", "ambient", "soundtrack"],
    { places: ["city"] }),
  kb("amsterdam", "city", [/\bamsterdam\b/i], "amsterdam-canal",
    ["reflective", "romantic", "nocturnal", "dreamlike"],
    ["amsterdam", "canal", "bicycle", "café"],
    ["electronic", "indie", "jazz", "folk"],
    { places: ["city"] }),
  kb("lisbon", "city", [/\blisbon\b/i, /\blisboa\b/i], "lisbon-fado",
    ["melancholy", "nostalgia", "romantic", "reflective"],
    ["lisbon", "fado", "coastal", "sunset"],
    ["folk", "jazz", "world", "ambient"],
    { places: ["city", "coast"] }),
];
