import { kb } from "./types";

/** Weak-signal entries — atmosphere hints only; never override genre/emotion/taste. */
export const MISC_CONTEXT_ENTRIES = [
  kb("architecture-gothic", "concept", [/\bgothic\s+(?:cathedral|architecture|church)\b/i, /\bbrutalist\b/i], "architecture-gothic",
    ["vintage", "melancholy", "cinematic", "wonder"],
    ["architecture", "gothic", "stone", "history"],
    ["classical", "ambient", "orchestral"],
    { signalWeight: 0.3, atmosphereOverActivity: false }),
  kb("animal-cat-cozy", "object", [/\bcat\b.*\b(?:window|rain|cozy)\b/i, /\bcozy\b.*\bcat\b/i], "cozy-interior",
    ["cozy", "reflective", "melancholy"],
    ["cat", "domestic", "quiet"],
    ["ambient", "folk", "indie"],
    { signalWeight: 0.25, atmosphereOverActivity: false }),
  kb("animal-dog-walk", "object", [/\bdog\s+walk\b/i, /\bwalking\s+(?:my\s+)?dog\b/i], "outdoor-walk",
    ["adventure", "reflective", "nostalgia"],
    ["dog", "walk", "park"],
    ["indie", "folk", "pop"],
    { signalWeight: 0.25, atmosphereOverActivity: false }),
  kb("colour-blue-hour", "concept", [/\bblue\s+hour\b/i, /\bindigo\b.*\bsky\b/i], "blue-hour",
    ["melancholy", "cinematic", "reflective", "nocturnal"],
    ["blue", "twilight", "evening"],
    ["ambient", "electronic", "jazz"],
    { signalWeight: 0.3, atmosphereOverActivity: false }),
  kb("colour-golden", "concept", [/\bgolden\b/i, /\bamber\b.*\blight\b/i], "golden-light",
    ["nostalgia", "romantic", "cozy", "cinematic"],
    ["golden", "warm", "glow"],
    ["folk", "indie", "jazz"],
    { signalWeight: 0.3, atmosphereOverActivity: false }),
  kb("object-vinyl", "object", [/\bvinyl\b/i, /\brecord\s+player\b/i, /\bturntable\b/i], "vinyl-nostalgia",
    ["nostalgia", "vintage", "cozy", "reflective"],
    ["vinyl", "analog", "records"],
    ["soul", "jazz", "rock", "indie"],
    { signalWeight: 0.35, atmosphereOverActivity: false }),
  kb("internet-doomscroll", "subculture", [/\bdoomscroll(?:ing)?\b/i, /\blate\s+night\s+scroll\b/i], "internet-late-night",
    ["nocturnal", "lonely", "reflective", "melancholy"],
    ["internet", "screen", "insomnia"],
    ["electronic", "ambient", "lofi"],
    { signalWeight: 0.3, atmosphereOverActivity: false }),
  kb("tv-stranger-things", "television", [/\bstranger\s+things\b/i], "eighties-retro",
    ["nostalgia", "foreboding", "adventure", "cinematic"],
    ["80s", "synth", "small-town", "mystery"],
    ["synth", "electronic", "pop", "rock"],
    { eraRange: { start: 1980, end: 1989 } }),
  kb("tv-breaking-bad", "television", [/\bbreaking\s+bad\b/i, /\balbuquerque\b/i], "desert-noir",
    ["foreboding", "suspense", "cinematic", "industrial"],
    ["desert", "crime", "tension"],
    ["rock", "electronic", "ambient", "country"],
    { places: ["desert"] }),
  kb("rainy-motorway", "concept", [/\brain(?:y)?\b.*\b(?:motorway|highway|motorway)\b/i, /\b(?:motorway|highway)\b.*\brain\b/i], "rainy-scene",
    ["melancholy", "reflective", "cinematic", "adventure"],
    ["rain", "motorway", "drive"],
    ["indie", "electronic", "rock"],
    { places: ["motorway"], weather: ["rain"], atmosphereOverActivity: true }),
];
