import { kb } from "./types";

export const AUTHOR_ENTRIES = [
  kb("agatha-christie", "author", [/\bagatha\s+christie\b/i, /\bpoirot\b/i, /\bmiss\s+marple\b/i], "cozy-mystery",
    ["mystery", "suspense", "vintage", "intellectual", "cozy"],
    ["british", "detective", "vintage", "mystery", "interwar"],
    ["jazz", "classical", "ambient", "folk", "soundtrack"],
    { themes: ["investigation", "secrets"], sceneConcepts: ["drawing-room-mystery", "whodunit"], places: ["library", "manor"], eraRange: { start: 1920, end: 1950 }, dominantEmotion: "tension" }),
  kb("sherlock-holmes", "author", [/\bsherlock\s+holmes\b/i, /\b221b\b/i, /\bconan\s+doyle\b/i, /\bbaker\s+street\b/i], "victorian-detective",
    ["mystery", "intellectual", "nocturnal", "vintage", "cinematic"],
    ["victorian", "london", "detective", "fog", "noir"],
    ["classical", "jazz", "ambient", "soundtrack", "folk"],
    { themes: ["investigation", "deduction"], sceneConcepts: ["victorian-london", "gaslight-noir"], weather: ["fog", "rain"], eraRange: { start: 1880, end: 1910 }, dominantEmotion: "tension" }),
  kb("stephen-king", "author", [/\bstephen\s+king\b/i, /\bshining\b/i], "horror-suspense",
    ["suspense", "foreboding", "uncanny", "nocturnal"],
    ["horror", "suspense", "americana", "unease"],
    ["ambient", "rock", "electronic", "classical", "soundtrack"],
    { themes: ["dread", "small-town"], dominantEmotion: "tension" }),
  kb("lovecraft", "author", [/\blovecraft\b/i, /\bcthulhu\b/i, /\beldritch\b/i, /\bcosmic\s+horror\b/i], "cosmic-horror",
    ["uncanny", "foreboding", "mystery", "dreamlike"],
    ["cosmic", "horror", "mythic", "dark"],
    ["ambient", "classical", "electronic", "metal", "soundtrack"],
    { dominantEmotion: "tension" }),
  kb("tolkien", "author", [/\btolkien\b/i, /\bmiddle\s+earth\b/i, /\blord\s+of\s+the\s+rings\b/i, /\bhobbit\b/i], "epic-fantasy",
    ["epic", "wonder", "adventure", "nostalgia"],
    ["fantasy", "mythic", "medieval", "adventure"],
    ["orchestral", "folk", "ambient", "classical"],
    { sceneConcepts: ["middle-earth", "fellowship"], places: ["forest", "mountain"], dominantEmotion: "wonder" }),
  kb("orwell", "author", [/\borwell\b/i, /\b1984\b/i, /\banimal\s+farm\b/i, /\bbig\s+brother\b/i], "dystopian",
    ["foreboding", "industrial", "reflective", "nocturnal"],
    ["dystopian", "political", "bleak"],
    ["electronic", "industrial", "ambient", "rock", "classical"],
    { dominantEmotion: "tension" }),
  kb("asimov", "author", [/\basimov\b/i, /\bfoundation\b/i, /\bisaac\s+asimov\b/i], "sci-fi-future",
    ["futuristic", "intellectual", "reflective", "wonder"],
    ["sci-fi", "future", "logic", "space"],
    ["electronic", "ambient", "orchestral", "classical"],
    { dominantEmotion: "wonder" }),
  kb("frank-herbert", "author", [/\bfrank\s+herbert\b/i, /\bdune\b/i, /\barrakis\b/i, /\bpaul\s+atreides\b/i], "desert-epic",
    ["epic", "futuristic", "mystery", "reflective"],
    ["sci-fi", "desert", "epic", "philosophical"],
    ["orchestral", "ambient", "electronic", "world", "soundtrack"],
    { places: ["desert"], dominantEmotion: "wonder" }),
  kb("hemingway", "author", [/\bhemingway\b/i, /\bernest\s+hemingway\b/i], "literary-adventure",
    ["adventure", "melancholy", "reflective", "nostalgia"],
    ["literary", "expat", "minimal", "sea"],
    ["jazz", "folk", "classical", "blues"],
    { dominantEmotion: "melancholy" }),
  kb("cormac-mccarthy", "author", [/\bcormac\s+mccarthy\b/i, /\broad\b/i], "desolate-americana",
    ["foreboding", "melancholy", "lonely", "cinematic"],
    ["americana", "desolate", "violence", "open-road"],
    ["folk", "country", "ambient", "classical"],
    { places: ["desert", "highway"], dominantEmotion: "tension" }),
  kb("victorian-detective", "literary-genre", [/\bvictorian\s+detective\b/i, /\bwhodunit\b/i], "victorian-detective",
    ["mystery", "vintage", "intellectual", "cozy"],
    ["victorian", "detective", "mystery"],
    ["classical", "jazz", "ambient", "folk"],
    { eraRange: { start: 1880, end: 1910 } }),
  kb("murder-mystery", "literary-genre", [/\bmurder\s+mystery\b/i, /\bsolving\s+a\s+murder\b/i, /\bdetective\s+story\b/i], "cozy-mystery",
    ["mystery", "suspense", "intellectual", "nocturnal"],
    ["detective", "mystery", "noir"],
    ["jazz", "classical", "ambient", "blues", "soundtrack"]),
  kb("small-town-horror", "literary-genre", [/\bsmall.?town\s+horror\b/i, /\bhorror\s+novel\b/i], "horror-suspense",
    ["foreboding", "suspense", "uncanny", "nostalgia"],
    ["horror", "small-town", "dread", "americana"],
    ["ambient", "rock", "electronic", "folk", "country"],
    { themes: ["isolation", "dread"], dominantEmotion: "tension" }),
  kb("cyberpunk-dystopia", "literary-genre", [/\bcyberpunk\s+dystopi[a]?\b/i, /\bdystopian\s+cyberpunk\b/i], "cyber-dystopia",
    ["futuristic", "foreboding", "industrial", "nocturnal"],
    ["cyberpunk", "dystopia", "neon", "surveillance"],
    ["electronic", "industrial", "ambient", "synth"],
    { dominantEmotion: "tension" }),
  kb("reading-context", "concept", [/\breading\b/i, /\bread(?:ing)?\s+(?:a\s+)?book\b/i], "literary-reading",
    ["reflective", "cozy", "intellectual"],
    ["literary", "quiet"],
    ["ambient", "classical", "jazz", "folk"],
    { places: ["library"], atmosphereOverActivity: false, signalWeight: 0.2 }),
];

export const FILM_TV_ENTRIES = [
  kb("blade-runner", "film", [/\bblade\s+runner\b/i], "cyberpunk-night",
    ["futuristic", "nocturnal", "melancholy", "cinematic"],
    ["cyberpunk", "neon", "rain", "dystopian"],
    ["electronic", "ambient", "synth", "jazz"],
    { weather: ["rain"], visual: ["neon"] }),
  kb("drive-movie", "film", [/\bdrive\b.*\b(?:movie|film|soundtrack|night)\b/i, /\bryan\s+gosling\b.*\bdrive\b/i], "neo-noir",
    ["nocturnal", "cinematic", "lonely", "foreboding"],
    ["noir", "neon", "synth", "la"],
    ["electronic", "synth", "ambient", "indie"],
    { places: ["city"] }),
  kb("interstellar", "film", [/\binterstellar\b/i], "space-epic",
    ["epic", "wonder", "melancholy", "cinematic"],
    ["space", "cosmos", "time", "organ"],
    ["orchestral", "ambient", "electronic", "classical"],
    { dominantEmotion: "wonder" }),
  kb("the-matrix", "film", [/\bthe\s+matrix\b/i, /\bmatrix\b.*\b(?:movie|film|neo)\b/i], "cyber-dystopia",
    ["futuristic", "industrial", "suspense", "cinematic"],
    ["cyber", "dystopia", "digital", "rebellion"],
    ["electronic", "industrial", "rock", "metal"],
    { dominantEmotion: "tension" }),
  kb("the-godfather", "film", [/\bthe\s+godfather\b/i, /\bgodfather\b/i], "mafia-noir",
    ["vintage", "cinematic", "foreboding", "melancholy"],
    ["mafia", "italian", "family", "noir"],
    ["classical", "jazz", "soundtrack", "orchestral"],
    { eraRange: { start: 1940, end: 1970 } }),
  kb("lotr-film", "film", [/\blord\s+of\s+the\s+rings\b.*\b(?:film|movie)\b/i], "epic-fantasy",
    ["epic", "wonder", "adventure", "nostalgia"],
    ["fantasy", "middle-earth", "quest"],
    ["orchestral", "folk", "ambient", "classical"]),
  kb("dark-knight", "film", [/\bdark\s+knight\b/i, /\bbatman\b.*\b(?:movie|film|gotham)\b/i], "gotham-noir",
    ["nocturnal", "foreboding", "cinematic", "industrial"],
    ["gotham", "hero", "noir", "urban"],
    ["orchestral", "electronic", "rock", "ambient"]),
  kb("lost-in-translation", "film", [/\blost\s+in\s+translation\b/i], "tokyo-night",
    ["lonely", "melancholy", "dreamlike", "nocturnal"],
    ["tokyo", "hotel", "jet-lag", "isolation"],
    ["electronic", "ambient", "indie", "jazz"],
    { places: ["city", "hotel"] }),
];

export const GAME_ENTRIES = [
  kb("cyberpunk-2077", "game", [/\bcyberpunk\s+2077\b/i, /\bnight\s+city\b/i], "cyberpunk-night",
    ["futuristic", "nocturnal", "industrial", "cinematic"],
    ["cyberpunk", "neon", "dystopia"],
    ["electronic", "industrial", "rock", "metal"]),
  kb("skyrim", "game", [/\bskyrim\b/i, /\btes\s+v\b/i], "epic-fantasy",
    ["epic", "adventure", "lonely", "wonder"],
    ["fantasy", "nordic", "dragon", "quest"],
    ["orchestral", "folk", "ambient", "classical"],
    { weather: ["snow"] }),
  kb("fallout", "game", [/\bfallout\b/i, /\bwasteland\b/i], "post-apocalyptic",
    ["foreboding", "nostalgia", "industrial", "lonely"],
    ["wasteland", "retro-future", "survival"],
    ["ambient", "electronic", "folk", "rock"]),
  kb("gta", "game", [/\b(?:grand\s+theft\s+auto|gta)\b/i], "gta-driving",
    ["urban", "nocturnal", "cinematic", "adventure"],
    ["gta", "city", "crime", "highway"],
    ["hip_hop", "electronic", "rock", "rnb"]),
  kb("red-dead-redemption", "game", [/\bred\s+dead\s+redemption\b/i, /\brdr2?\b/i], "western-frontier",
    ["nostalgia", "melancholy", "adventure", "lonely"],
    ["western", "frontier", "outlaw", "americana"],
    ["country", "folk", "ambient", "orchestral"]),
  kb("mass-effect", "game", [/\bmass\s+effect\b/i, /\bshepard\b/i], "space-epic",
    ["epic", "futuristic", "cinematic", "wonder"],
    ["sci-fi", "space", "crew", "galaxy"],
    ["electronic", "orchestral", "ambient", "rock"]),
  kb("minecraft", "game", [/\bminecraft\b/i], "minecraft-calm",
    ["cozy", "reflective", "wonder", "nostalgia"],
    ["minecraft", "building", "sandbox", "calm"],
    ["ambient", "electronic", "lofi", "indie"]),
  kb("elden-ring", "game", [/\belden\s+ring\b/i, /\bfromsoftware\b/i], "dark-fantasy",
    ["foreboding", "epic", "melancholy", "wonder"],
    ["dark-fantasy", "medieval", "boss", "lonely"],
    ["orchestral", "ambient", "metal", "classical"]),
];
