import { kb } from "./types";

export const ERA_ENTRIES = [
  kb("victorian-era", "era", [/\bvictorian\b/i], "victorian-detective",
    ["vintage", "mystery", "intellectual", "nostalgia"],
    ["victorian", "gaslight", "industrial-age"],
    ["classical", "folk", "ambient", "jazz"],
    { eraRange: { start: 1837, end: 1901 } }),
  kb("1920s", "era", [/\b1920s\b/i, /\broaring\s+twenties\b/i], "jazz-age",
    ["vintage", "nostalgia", "cinematic", "adventure"],
    ["1920s", "jazz-age", "speakeasy"],
    ["jazz", "blues", "classical", "swing"],
    { eraRange: { start: 1920, end: 1929 } }),
  kb("1940s", "era", [/\b1940s\b/i, /\bpost.?war\b/i], "post-war",
    ["nostalgia", "melancholy", "vintage", "reflective"],
    ["1940s", "wartime", "swing"],
    ["jazz", "swing", "classical", "folk"],
    { eraRange: { start: 1940, end: 1949 } }),
  kb("1970s", "era", [/\b1970s\b/i, /\bseventies\b/i], "seventies-retro",
    ["nostalgia", "vintage", "adventure", "reflective"],
    ["1970s", "disco", "rock", "analog"],
    ["rock", "soul", "funk", "disco"],
    { eraRange: { start: 1970, end: 1979 } }),
  kb("1980s", "era", [/\b1980s\b/i, /\beighties\b/i], "eighties-retro",
    ["nostalgia", "futuristic", "cinematic", "adventure"],
    ["1980s", "synth", "neon", "retro"],
    ["synth", "pop", "rock", "electronic"],
    { eraRange: { start: 1980, end: 1989 } }),
  kb("1990s", "era", [/\b1990s\b/i, /\bnineties\b/i], "nineties-retro",
    ["nostalgia", "urban", "reflective", "adventure"],
    ["1990s", "rave", "grunge", "hip-hop"],
    ["rock", "hip_hop", "electronic", "indie"],
    { eraRange: { start: 1990, end: 1999 } }),
  kb("y2k", "era", [/\by2k\b/i, /\bearly\s+internet\b/i, /\bdot.?com\b/i], "y2k-internet",
    ["futuristic", "nostalgia", "dreamlike", "cinematic"],
    ["y2k", "internet", "digital", "millennium"],
    ["electronic", "pop", "synth", "hip_hop"],
    { eraRange: { start: 1998, end: 2003 } }),
  kb("cold-war", "era", [/\bcold\s+war\b/i], "cold-war",
    ["foreboding", "industrial", "vintage", "suspense"],
    ["cold-war", "espionage", "tension"],
    ["electronic", "classical", "jazz", "ambient"],
    { eraRange: { start: 1947, end: 1991 } }),
];

export const LIFE_MOMENT_ENTRIES = [
  kb("moving-house", "life-moment", [/\bmoving\s+(?:house|home|apartment|flat)\b/i, /\bnew\s+apartment\b/i], "life-transition",
    ["reflective", "nostalgia", "melancholy", "adventure"],
    ["moving", "transition", "boxes", "change"],
    ["indie", "folk", "ambient", "pop"]),
  kb("starting-university", "life-moment", [/\bstarting\s+university\b/i, /\bfreshers\b/i, /\bcollege\b.*\bfirst\b/i], "new-chapter",
    ["adventure", "nostalgia", "reflective", "wonder"],
    ["university", "campus", "youth", "freedom"],
    ["indie", "pop", "rock", "electronic"]),
  kb("first-job", "life-moment", [/\bfirst\s+job\b/i, /\bnew\s+job\b/i, /\bstarting\s+work\b/i], "new-chapter",
    ["adventure", "reflective", "suspense"],
    ["career", "commute", "adult"],
    ["indie", "pop", "electronic", "hip_hop"]),
  kb("retirement", "life-moment", [/\bretirement\b/i, /\bretired\b/i], "life-reflection",
    ["nostalgia", "reflective", "cozy", "melancholy"],
    ["retirement", "memory", "slow"],
    ["jazz", "classical", "folk", "ambient"]),
  kb("breakup", "life-moment", [/\bbreakup\b/i, /\bbreak\s+up\b/i, /\bheartbreak\b/i], "heartbreak",
    ["melancholy", "lonely", "reflective", "nostalgia"],
    ["breakup", "loss", "rain"],
    ["indie", "rnb", "pop", "soul"],
    { weather: ["rain"], dominantEmotion: "melancholy" }),
  kb("road-trip", "life-moment", [/\broad\s+trip\b/i, /\bdriving\b.*\b(?:across|through|home)\b/i], "road-trip",
    ["adventure", "nostalgia", "reflective", "cinematic"],
    ["road-trip", "highway", "freedom"],
    ["rock", "indie", "country", "electronic"],
    { places: ["highway"], atmosphereOverActivity: true }),
  kb("night-shift", "life-moment", [/\bnight\s+shift\b/i, /\bworking\s+late\b/i, /\blate.?night\s+coding\b/i], "night-shift",
    ["nocturnal", "lonely", "industrial", "reflective"],
    ["night-shift", "work", "fluorescent"],
    ["electronic", "ambient", "indie", "lofi"],
    { times: ["night", "late-night"] }),
  kb("last-train-home", "life-moment", [/\blast\s+train\b/i, /\bmissed\s+the\s+last\s+train\b/i], "last-train",
    ["lonely", "melancholy", "nocturnal", "reflective"],
    ["last-train", "commute", "platform"],
    ["indie", "electronic", "ambient", "jazz"],
    { places: ["train", "station"], atmosphereOverActivity: true }),
  kb("travelling-alone", "life-moment", [/\btravelling\s+alone\b/i, /\btraveling\s+alone\b/i, /\bsolo\s+trip\b/i], "solo-travel",
    ["lonely", "adventure", "reflective", "wonder"],
    ["solo-travel", "transit", "foreign"],
    ["indie", "electronic", "folk", "ambient"]),
  kb("building-something", "life-moment", [/\bbuilding\s+something\b/i, /\bworking\s+on\s+a\s+project\b/i], "maker-focus",
    ["reflective", "industrial", "cozy", "intellectual"],
    ["maker", "craft", "workshop"],
    ["electronic", "ambient", "indie", "rock"]),
  kb("garage-work", "life-moment", [/\bworking\s+in\s+(?:a\s+)?garage\b/i, /\bfixing\s+(?:a\s+|my\s+)?(?:volvo|car|bike|motorcycle)\b/i], "garage-midnight",
    ["nocturnal", "industrial", "reflective", "nostalgia", "cozy"],
    ["garage", "mechanical", "craft"],
    ["blues", "indie", "rock", "folk"],
    { places: ["garage"], atmosphereOverActivity: true }),
];

export const WEATHER_ENTRIES = [
  kb("heavy-rain", "weather", [/\b(?:heavy\s+)?rain\b/i, /\brainy\b/i, /\bdrizzle\b/i], "rainy-scene",
    ["melancholy", "reflective", "cozy", "cinematic"],
    ["rain", "wet", "storm"],
    ["indie", "electronic", "jazz", "ambient"],
    { weather: ["rain"], signalWeight: 0.45 }),
  kb("storm", "weather", [/\bstorm\b/i, /\bthunder\b/i, /\blightning\b/i], "storm-scene",
    ["foreboding", "suspense", "cinematic", "suspense"],
    ["storm", "thunder", "dramatic"],
    ["rock", "electronic", "orchestral", "ambient"],
    { weather: ["storm"], signalWeight: 0.45 }),
  kb("fog-scene", "weather", [/\bfog(?:gy)?\b/i, /\bmist(?:y)?\b/i], "fog-scene",
    ["mystery", "lonely", "dreamlike", "nocturnal"],
    ["fog", "mist", "haze"],
    ["ambient", "classical", "electronic", "jazz"],
    { weather: ["fog"], signalWeight: 0.45 }),
  kb("snow-scene", "weather", [/\bsnow(?:y|ing)?\b/i, /\bwinter\b/i], "winter-scene",
    ["lonely", "cozy", "melancholy", "nostalgia"],
    ["snow", "winter", "cold"],
    ["ambient", "classical", "indie", "folk"],
    { weather: ["snow"], signalWeight: 0.45 }),
  kb("heatwave", "weather", [/\bheatwave\b/i, /\bhot\s+summer\b/i], "summer-heat",
    ["adventure", "nostalgia", "reflective"],
    ["heat", "summer", "sun"],
    ["pop", "reggae", "electronic", "hip_hop"],
    { weather: ["heat"], signalWeight: 0.45 }),
  kb("sunrise-scene", "weather", [/\bsunrise\b/i, /\bdawn\b/i], "sunrise-scene",
    ["wonder", "reflective", "adventure", "cinematic"],
    ["sunrise", "dawn", "new-day"],
    ["ambient", "electronic", "indie", "classical"],
    { times: ["sunrise"], signalWeight: 0.45 }),
  kb("sunset-scene", "weather", [/\bsunset\b/i, /\bgolden\s+hour\b/i, /\bdusk\b/i], "sunset-scene",
    ["nostalgia", "romantic", "reflective", "cinematic"],
    ["sunset", "golden-hour", "evening"],
    ["indie", "folk", "electronic", "jazz"],
    { times: ["sunset"], signalWeight: 0.45 }),
];

export const TRANSPORT_OBJECT_ENTRIES = [
  kb("volvo-garage", "transport", [/\bvolvo\b/i, /\bsaab\b/i, /\be46\b/i, /\bmx-?5\b/i], "garage-midnight",
    ["nostalgia", "reflective", "industrial", "cozy"],
    ["volvo", "project-car", "mechanical"],
    ["blues", "indie", "rock", "folk"],
    { places: ["garage"], atmosphereOverActivity: true }),
  kb("motorbike-ride", "transport", [/\bmotor(?:cycle|bike)\b/i, /\bbike\s+ride\b/i], "motorbike-open-road",
    ["adventure", "cinematic", "nocturnal"],
    ["motorbike", "open-road", "wind"],
    ["rock", "electronic", "indie", "metal"],
    { places: ["highway"], times: ["sunset", "night"] }),
  kb("neo-noir-city", "concept", [/\bneo.?noir\b/i, /\bnoir\s+city\b/i], "neo-noir",
    ["nocturnal", "mystery", "cinematic", "lonely"],
    ["noir", "urban", "neon"],
    ["jazz", "electronic", "ambient", "trip_hop"]),
  kb("tokyo-after-midnight", "location", [/\btokyo\b.*\b(?:3\s?am|midnight|after\s+midnight)\b/i, /\b(?:3\s?am|midnight).*\btokyo\b/i], "tokyo-night",
    ["nocturnal", "urban", "lonely", "cinematic", "dreamlike"],
    ["tokyo", "neon", "late-night"],
    ["electronic", "ambient", "indie", "jazz"],
    { atmosphereOverActivity: true }),
  kb("paris-cafe-rain", "location", [
    /\bparis(?:ian)?\s+caf[eé]\b/i,
    /\bparis(?:ian)?\b.*\b(?:caf[eé]|cafe)\b/i,
    /\bparis\b.*\brain\b/i,
    /\bparisian\b.*\brain\b/i,
  ], "paris-cafe",
    ["romantic", "melancholy", "reflective", "cozy"],
    ["paris", "café", "french", "romantic"],
    ["jazz", "chanson", "classical", "indie"],
    { weather: ["rain"], atmosphereOverActivity: true }),
];

export const HOBBY_JOB_SUBCULTURE_ENTRIES = [
  kb("late-night-coding", "hobby", [/\blate.?night\s+cod(?:e|ing)\b/i, /\bcoding\s+at\s+night\b/i], "night-shift",
    ["nocturnal", "intellectual", "lonely", "industrial"],
    ["coding", "developer", "terminal"],
    ["electronic", "ambient", "lofi", "synth"]),
  kb("warehouse-rave", "subculture", [/\bwarehouse\s+rave\b/i, /\bunderground\s+rave\b/i], "berlin-warehouse",
    ["adventure", "industrial", "nocturnal", "cinematic"],
    ["rave", "warehouse", "techno"],
    ["electronic", "techno", "house", "ambient"]),
  kb("skate-culture", "subculture", [/\bskate(?:board|ing)?\b/i, /\bpunk\s+scene\b/i], "skate-punk-scene",
    ["adventure", "nostalgia", "urban", "adventure"],
    ["skate", "punk", "youth"],
    ["punk", "rock", "indie", "hip_hop"]),
];
