/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * K_WALAH Emotional AI Spotify DJ API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Spotify OAuth callback
 */
export const AuthCallbackQueryParams = zod.object({
  "code": zod.coerce.string().optional(),
  "error": zod.coerce.string().optional()
})


/**
 * @summary Logout
 */
export const AuthLogoutResponse = zod.object({
  "message": zod.string()
})


/**
 * @summary Get current user profile
 */
export const GetMeResponse = zod.object({
  "id": zod.string(),
  "displayName": zod.string(),
  "email": zod.string().nullish(),
  "avatarUrl": zod.string().nullish(),
  "country": zod.string().nullish()
})


/**
 * @summary Get liked songs cache status
 */
export const GetCacheStatusResponse = zod.object({
  "synced": zod.boolean(),
  "totalTracks": zod.number(),
  "lastSyncedAt": zod.string().nullable(),
  "isSyncing": zod.boolean(),
  "syncProgress": zod.number().nullish(),
  "syncTotal": zod.number().nullish()
})


/**
 * @summary Trigger sync of liked songs
 */
export const SyncLikedSongsResponse = zod.object({
  "message": zod.string(),
  "started": zod.boolean()
})


/**
 * @summary Generate emotional playlist
 */

export const generatePlaylistBodyModeDefault = `balanced`;
export const generatePlaylistBodyLengthDefault = 40;
export const generatePlaylistBodyLengthMin = 20;
export const generatePlaylistBodyLengthMax = 100;



export const GeneratePlaylistBody = zod.object({
  "vibe": zod.string().min(1),
  "mode": zod.enum(['strict', 'balanced', 'chaotic']).default(generatePlaylistBodyModeDefault),
  "length": zod.number().min(generatePlaylistBodyLengthMin).max(generatePlaylistBodyLengthMax).default(generatePlaylistBodyLengthDefault),
  "referencePlaylist": zod.string().max(500).optional(),
  "varietyBoost": zod.boolean().optional(),
  "filmScene": zod.string().max(120).optional(),
  "sceneId": zod.string().max(120).optional(),
  "noLibraryMode": zod.boolean().optional(),
})

export const GeneratePlaylistResponse = zod.object({
  "playlistId": zod.string(),
  "playlistUrl": zod.string(),
  "name": zod.string(),
  "vibe": zod.string(),
  "mode": zod.string(),
  "tracks": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "artist": zod.string(),
  "album": zod.string(),
  "albumArt": zod.string().nullish(),
  "durationMs": zod.number().optional(),
  "energy": zod.number().nullish(),
  "valence": zod.number().nullish(),
  "tempo": zod.number().nullish(),
  "score": zod.number().optional()
})),
  "emotionProfile": zod.object({
  "energy": zod.number(),
  "valence": zod.number(),
  "tension": zod.number(),
  "nostalgia": zod.number(),
  "calm": zod.number(),
  "environment": zod.string().nullish(),
  "timeOfDay": zod.string().nullish(),
  "motionState": zod.string().nullish()
}),
  "totalTracks": zod.number().optional()
})


/**
 * @summary Get generated playlist history
 */
export const GetHistoryResponseItem = zod.object({
  "id": zod.number(),
  "playlistId": zod.string(),
  "playlistUrl": zod.string(),
  "name": zod.string(),
  "vibe": zod.string(),
  "mode": zod.string(),
  "trackCount": zod.number(),
  "createdAt": zod.string(),
  "emotionProfile": zod.object({
  "energy": zod.number(),
  "valence": zod.number(),
  "tension": zod.number(),
  "nostalgia": zod.number(),
  "calm": zod.number(),
  "environment": zod.string().nullish(),
  "timeOfDay": zod.string().nullish(),
  "motionState": zod.string().nullish()
}).optional()
})
export const GetHistoryResponse = zod.array(GetHistoryResponseItem)


