/**
 * Batch 2 scene encyclopedia — import into scene-library.ts.
 * Target: grow toward 500+ total entries over multiple PRs.
 */

import type { SceneEntry } from "./scene-types";

export const SCENE_LIBRARY_EXTENDED: SceneEntry[] = [
  {
    id: "airport_goodbye",
    terms: ["airport goodbye", "seeing them off at the airport", "departure gate tears"],
    environment: "transit",
    energy: 0.28,
    valence: 0.3,
    tension: 0.55,
    nostalgia: 0.65,
    calm: 0.2,
    journeyArc: "linear_fall",
    qualities: ["loss", "transition"],
    socialContext: "partner",
  },
  {
    id: "airport_reunion",
    terms: ["airport reunion", "arrivals hall hug", "picking them up at the airport"],
    environment: "transit",
    energy: 0.55,
    valence: 0.72,
    tension: 0.2,
    nostalgia: 0.35,
    calm: 0.25,
    journeyArc: "linear_rise",
    qualities: ["joy", "anticipation"],
    socialContext: "partner",
  },
  {
    id: "empty_office_after_work",
    terms: ["empty office after work", "last one in the office", "office alone evening"],
    time: "evening",
    environment: "office",
    energy: 0.22,
    valence: 0.38,
    tension: 0.3,
    nostalgia: 0.4,
    calm: 0.35,
    journeyArc: "recovery",
    qualities: ["decompression", "solitude"],
    lifeSituation: "after_work",
    socialContext: "alone",
  },
  {
    id: "friday_after_work",
    terms: ["friday after work", "finishing work on a friday", "friday evening freedom"],
    time: "evening",
    energy: 0.58,
    valence: 0.65,
    tension: 0.15,
    nostalgia: 0.25,
    calm: 0.2,
    journeyArc: "linear_rise",
    qualities: ["release", "anticipation"],
    lifeSituation: "after_work",
  },
  {
    id: "winter_morning_commute",
    terms: ["winter morning commute", "cold commute winter", "dark morning bus"],
    season: "winter",
    time: "morning",
    motion: "transit",
    energy: 0.35,
    valence: 0.4,
    tension: 0.25,
    nostalgia: 0.35,
    calm: 0.3,
    journeyArc: "slow_burn",
    qualities: ["routine", "resilience"],
  },
  {
    id: "gym_before_sunrise",
    terms: ["gym before sunrise", "early gym session", "5am workout"],
    time: "morning",
    environment: "gym",
    energy: 0.65,
    valence: 0.5,
    tension: 0.35,
    nostalgia: 0.1,
    calm: 0.2,
    journeyArc: "linear_rise",
    qualities: ["discipline", "solo_focus"],
    socialContext: "alone",
  },
  {
    id: "walking_through_fog",
    terms: ["walking through fog", "foggy morning walk", "misty path alone"],
    environment: "outdoor",
    energy: 0.25,
    valence: 0.42,
    tension: 0.3,
    nostalgia: 0.5,
    calm: 0.45,
    journeyArc: "slow_burn",
    qualities: ["liminality", "introspection"],
    socialContext: "alone",
  },
  {
    id: "night_bus_home",
    terms: ["night bus home", "late bus alone", "night bus window"],
    time: "late_night",
    motion: "transit",
    energy: 0.2,
    valence: 0.38,
    tension: 0.28,
    nostalgia: 0.55,
    calm: 0.32,
    journeyArc: "recovery",
    qualities: ["decompression", "urban"],
    socialContext: "alone",
  },
  {
    id: "city_lights_taxi",
    terms: ["city lights from a taxi", "taxi window city night", "back seat taxi rain"],
    time: "late_night",
    environment: "urban",
    motion: "driving",
    energy: 0.3,
    valence: 0.45,
    tension: 0.35,
    nostalgia: 0.6,
    calm: 0.28,
    journeyArc: "wave",
    qualities: ["transition", "reflection"],
  },
  {
    id: "exam_season",
    terms: ["exam season", "revision stress", "finals week studying"],
    energy: 0.4,
    valence: 0.35,
    tension: 0.65,
    nostalgia: 0.2,
    calm: 0.15,
    journeyArc: "linear_rise",
    qualities: ["pressure", "focus"],
    lifeSituation: "university",
  },
  {
    id: "first_paycheck",
    terms: ["first paycheck", "first salary", "first real job pay day"],
    energy: 0.62,
    valence: 0.7,
    tension: 0.2,
    nostalgia: 0.3,
    calm: 0.2,
    journeyArc: "peak_release",
    qualities: ["pride", "optimism"],
    lifeSituation: "starting_over",
  },
  {
    id: "sunday_evening_dread",
    terms: ["sunday evening dread", "sunday scaries", "monday tomorrow anxiety"],
    time: "evening",
    energy: 0.28,
    valence: 0.32,
    tension: 0.5,
    nostalgia: 0.25,
    calm: 0.22,
    journeyArc: "recovery",
    qualities: ["anticipation", "low_grade_anxiety"],
  },
  {
    id: "social_recovery",
    terms: ["social recovery", "need alone time after party", "introvert recharge"],
    energy: 0.18,
    valence: 0.45,
    tension: 0.15,
    nostalgia: 0.2,
    calm: 0.55,
    journeyArc: "recovery",
    qualities: ["decompression"],
    socialContext: "alone",
    lifeSituation: "social_recovery",
  },
  {
    id: "date_night_in",
    terms: ["date night in", "cooking together evening", "stay in date night"],
    energy: 0.38,
    valence: 0.62,
    tension: 0.1,
    nostalgia: 0.25,
    calm: 0.4,
    journeyArc: "slow_burn",
    qualities: ["warmth", "intimacy"],
    socialContext: "partner",
  },
  {
    id: "family_gathering",
    terms: ["family gathering", "big family dinner", "relatives visiting"],
    energy: 0.45,
    valence: 0.58,
    tension: 0.25,
    nostalgia: 0.55,
    calm: 0.25,
    journeyArc: "wave",
    qualities: ["warmth", "complexity"],
    socialContext: "family",
    memoryWeight: 0.6,
  },
  {
    id: "house_party",
    terms: ["house party", "kitchen party", "friends over loud"],
    energy: 0.72,
    valence: 0.68,
    tension: 0.2,
    nostalgia: 0.2,
    calm: 0.1,
    journeyArc: "peak_release",
    qualities: ["social_connection", "chaos"],
    socialContext: "party",
  },
  {
    id: "university_nostalgia",
    terms: ["university nostalgia", "college years", "uni halls memories"],
    energy: 0.38,
    valence: 0.52,
    tension: 0.12,
    nostalgia: 0.85,
    calm: 0.28,
    journeyArc: "wave",
    qualities: ["memory", "youth"],
    memoryWeight: 0.85,
    lifeSituation: "university",
  },
  {
    id: "first_relationship",
    terms: ["first relationship", "first love songs", "teenage love nostalgia"],
    energy: 0.42,
    valence: 0.55,
    tension: 0.2,
    nostalgia: 0.88,
    calm: 0.25,
    journeyArc: "slow_burn",
    qualities: ["memory", "innocence"],
    memoryWeight: 0.9,
  },
  {
    id: "old_friends_reunion",
    terms: ["old friends reunion", "seeing old friends again", "friends from school meetup"],
    energy: 0.52,
    valence: 0.65,
    tension: 0.15,
    nostalgia: 0.75,
    calm: 0.2,
    journeyArc: "peak_release",
    qualities: ["memory", "joy"],
    socialContext: "friends",
    memoryWeight: 0.7,
  },
  {
    id: "winter_sadness",
    terms: ["winter sadness", "january blues", "short days depressed"],
    season: "winter",
    energy: 0.2,
    valence: 0.28,
    tension: 0.35,
    nostalgia: 0.45,
    calm: 0.35,
    journeyArc: "recovery",
    qualities: ["seasonal", "melancholy"],
  },
  {
    id: "spring_optimism",
    terms: ["spring optimism", "everything blooming", "march hope"],
    season: "spring",
    energy: 0.48,
    valence: 0.62,
    tension: 0.15,
    nostalgia: 0.2,
    calm: 0.3,
    journeyArc: "linear_rise",
    qualities: ["renewal", "optimism"],
  },
  {
    id: "summer_freedom",
    terms: ["summer freedom", "long summer days", "heatwave carefree"],
    season: "summer",
    energy: 0.58,
    valence: 0.68,
    tension: 0.1,
    nostalgia: 0.4,
    calm: 0.22,
    journeyArc: "peak_release",
    qualities: ["freedom", "youth"],
    memoryWeight: 0.5,
  },
  {
    id: "autumn_nostalgia",
    terms: ["autumn nostalgia", "october melancholy", "fall nostalgia cozy"],
    season: "autumn",
    energy: 0.3,
    valence: 0.45,
    tension: 0.2,
    nostalgia: 0.75,
    calm: 0.38,
    journeyArc: "slow_burn",
    qualities: ["seasonal", "warmth"],
  },
  {
    id: "graduation_day",
    terms: ["graduation day", "cap and gown", "finished university"],
    energy: 0.55,
    valence: 0.65,
    tension: 0.35,
    nostalgia: 0.5,
    calm: 0.2,
    journeyArc: "peak_release",
    qualities: ["transition", "pride"],
    lifeSituation: "graduation",
  },
  {
    id: "holiday_airport",
    terms: ["holiday airport", "flying on holiday", "vacation departure excitement"],
    environment: "transit",
    energy: 0.52,
    valence: 0.68,
    tension: 0.25,
    nostalgia: 0.2,
    calm: 0.22,
    journeyArc: "linear_rise",
    qualities: ["anticipation", "escape"],
    lifeSituation: "holiday",
  },
  {
    id: "road_trip_solo",
    terms: ["road trip solo", "driving alone cross country", "solo highway journey"],
    motion: "driving",
    energy: 0.4,
    valence: 0.48,
    tension: 0.2,
    nostalgia: 0.55,
    calm: 0.32,
    journeyArc: "slow_burn",
    qualities: ["freedom", "introspection"],
    socialContext: "alone",
  },
  {
    id: "rebuilding_confidence",
    terms: ["rebuilding confidence", "getting confidence back", "learning to trust myself again"],
    energy: 0.45,
    valence: 0.55,
    tension: 0.3,
    nostalgia: 0.25,
    calm: 0.35,
    journeyArc: "linear_rise",
    qualities: ["growth", "resilience"],
    lifeSituation: "rebuilding",
  },
  {
    id: "grieving_grateful",
    terms: ["grieving but grateful", "sad and grateful", "loss and gratitude"],
    energy: 0.25,
    valence: 0.42,
    tension: 0.45,
    nostalgia: 0.7,
    calm: 0.35,
    journeyArc: "recovery",
    qualities: ["complexity", "bittersweet"],
    lifeSituation: "grieving",
  },
  {
    id: "lonely_peaceful",
    terms: ["lonely but peaceful", "alone and peaceful", "lonely peaceful night"],
    energy: 0.18,
    valence: 0.48,
    tension: 0.2,
    nostalgia: 0.45,
    calm: 0.55,
    journeyArc: "slow_burn",
    qualities: ["contradiction", "solitude"],
    socialContext: "alone",
  },
  {
    id: "happy_nostalgic",
    terms: ["happy and nostalgic", "happy nostalgic", "bittersweet happy"],
    energy: 0.42,
    valence: 0.62,
    tension: 0.25,
    nostalgia: 0.75,
    calm: 0.3,
    journeyArc: "wave",
    qualities: ["contradiction", "memory"],
  },
  {
    id: "excited_nervous",
    terms: ["excited and nervous", "nervous excited", "butterflies before big thing"],
    energy: 0.55,
    valence: 0.52,
    tension: 0.55,
    nostalgia: 0.15,
    calm: 0.15,
    journeyArc: "linear_rise",
    qualities: ["contradiction", "anticipation"],
  },
  {
    id: "hospital_waiting",
    terms: ["hospital waiting room", "waiting at hospital", "hospital anxiety waiting"],
    energy: 0.22,
    valence: 0.3,
    tension: 0.6,
    nostalgia: 0.2,
    calm: 0.18,
    journeyArc: "recovery",
    qualities: ["vulnerability", "waiting"],
  },
  {
    id: "wedding_morning",
    terms: ["wedding morning", "getting ready wedding", "morning of the wedding"],
    time: "morning",
    energy: 0.5,
    valence: 0.7,
    tension: 0.4,
    nostalgia: 0.35,
    calm: 0.2,
    journeyArc: "linear_rise",
    qualities: ["anticipation", "joy"],
  },
  {
    id: "new_job_first_day",
    terms: ["first day new job", "new job nerves", "starting new job monday"],
    energy: 0.48,
    valence: 0.5,
    tension: 0.55,
    nostalgia: 0.15,
    calm: 0.2,
    journeyArc: "linear_rise",
    qualities: ["anticipation", "growth"],
    lifeSituation: "starting_over",
  },
  {
    id: "rain_on_windscreen",
    terms: ["rain on the windscreen", "rain on windshield", "rain on the window driving"],
    environment: "rainy",
    motion: "driving",
    energy: 0.25,
    valence: 0.4,
    tension: 0.32,
    nostalgia: 0.55,
    calm: 0.35,
    journeyArc: "slow_burn",
    qualities: ["focus", "isolation"],
  },
  {
    id: "late_night_motorway",
    terms: ["late-night motorway", "late night motorway", "motorway alone night"],
    time: "late_night",
    motion: "driving",
    energy: 0.32,
    valence: 0.42,
    tension: 0.28,
    nostalgia: 0.62,
    calm: 0.3,
    journeyArc: "slow_burn",
    qualities: ["motion", "reflection"],
  },
];
