import type { SceneEntry } from "./scene-types";

/** Compound human-moment scenes from master tag expansion. */
export const SCENE_LIBRARY_MASTER: SceneEntry[] = [
  {
    id: "golden_hour_drive_friends",
    terms: [
      "golden hour drive with friends",
      "sunset drive friends",
      "evening road trip friends",
    ],
    time: "evening",
    motion: "driving",
    energy: 0.48,
    valence: 0.62,
    tension: 0.1,
    nostalgia: 0.55,
    calm: 0.22,
    journeyArc: "wave",
    qualities: ["warmth", "friendship", "memory"],
    socialContext: "friends",
    memoryWeight: 0.55,
  },
  {
    id: "late_summer_evening_friends_drive",
    terms: [
      "late summer evening driving home from seeing old friends",
      "driving home from seeing friends",
      "after seeing old friends drive home",
    ],
    time: "evening",
    motion: "driving",
    energy: 0.38,
    valence: 0.52,
    tension: 0.12,
    nostalgia: 0.72,
    calm: 0.28,
    journeyArc: "slow_burn",
    qualities: ["nostalgia", "transition", "reflection"],
    socialContext: "friends",
    memoryWeight: 0.7,
  },
  {
    id: "rain_on_windscreen_night",
    terms: ["rain on windscreen at night", "rain on the windscreen night drive", "wet windscreen night"],
    environment: "rainy",
    motion: "driving",
    time: "late_night",
    energy: 0.22,
    valence: 0.38,
    tension: 0.35,
    nostalgia: 0.65,
    calm: 0.32,
    journeyArc: "slow_burn",
    qualities: ["cinematic", "introspection", "isolation"],
    socialContext: "alone",
  },
  {
    id: "morning_commute_rain",
    terms: ["rainy morning commute", "wet morning commute", "rain on the way to work"],
    time: "morning",
    motion: "transit",
    environment: "rainy",
    energy: 0.35,
    valence: 0.4,
    tension: 0.2,
    nostalgia: 0.2,
    calm: 0.25,
    journeyArc: "linear_rise",
    lifeSituation: "after_work",
  },
  {
    id: "friday_afternoon_freedom",
    terms: ["friday afternoon freedom", "friday afternoon energy", "last hour friday work"],
    time: "afternoon",
    energy: 0.58,
    valence: 0.65,
    tension: 0.12,
    nostalgia: 0.15,
    calm: 0.15,
    journeyArc: "linear_rise",
    qualities: ["release", "anticipation"],
  },
  {
    id: "sunday_evening_reset",
    terms: ["sunday evening reset", "sunday scaries soft", "pre monday sunday"],
    time: "evening",
    energy: 0.28,
    valence: 0.42,
    tension: 0.35,
    nostalgia: 0.25,
    calm: 0.35,
    journeyArc: "recovery",
    qualities: ["reset", "low_anxiety"],
  },
  {
    id: "empty_train_window",
    terms: ["empty train window seat", "window seat train alone", "empty carriage train"],
    motion: "transit",
    energy: 0.2,
    valence: 0.42,
    tension: 0.2,
    nostalgia: 0.55,
    calm: 0.38,
    journeyArc: "recovery",
    socialContext: "alone",
  },
  {
    id: "night_bus_home",
    terms: ["night bus home alone", "last bus home night", "night bus window"],
    time: "late_night",
    motion: "transit",
    energy: 0.18,
    valence: 0.38,
    tension: 0.25,
    nostalgia: 0.58,
    calm: 0.3,
    journeyArc: "slow_burn",
    socialContext: "alone",
  },
  {
    id: "city_rooftop_night",
    terms: ["rooftop at night", "city rooftop night", "rooftop city lights"],
    time: "late_night",
    environment: "urban",
    energy: 0.32,
    valence: 0.45,
    tension: 0.28,
    nostalgia: 0.5,
    calm: 0.25,
    journeyArc: "wave",
    qualities: ["liminality", "urban"],
  },
  {
    id: "exam_all_nighter",
    terms: ["exam tomorrow all nighter", "revision all night", "cramming all night"],
    time: "late_night",
    environment: "library",
    energy: 0.42,
    valence: 0.35,
    tension: 0.65,
    nostalgia: 0.1,
    calm: 0.1,
    journeyArc: "linear_rise",
    lifeSituation: "university",
  },
  {
    id: "heartbroken_healing",
    terms: ["heartbroken but healing", "healing after heartbreak", "getting over heartbreak"],
    energy: 0.28,
    valence: 0.38,
    tension: 0.4,
    nostalgia: 0.35,
    calm: 0.3,
    journeyArc: "recovery",
    qualities: ["contradiction", "growth"],
    lifeSituation: "breakup",
  },
  {
    id: "forgotten_library_archaeology",
    terms: [
      "hidden corners of your library",
      "music you forgot you loved",
      "songs from another life",
      "your old soundtrack",
    ],
    energy: 0.35,
    valence: 0.48,
    tension: 0.15,
    nostalgia: 0.85,
    calm: 0.25,
    journeyArc: "wave",
    qualities: ["archaeology", "memory", "discovery"],
    memoryWeight: 0.9,
  },
  {
    id: "lockdown_indoor",
    terms: ["lockdown memories", "lockdown era playlist", "stuck inside lockdown"],
    environment: "indoor",
    energy: 0.22,
    valence: 0.4,
    tension: 0.2,
    nostalgia: 0.75,
    calm: 0.35,
    journeyArc: "slow_burn",
    memoryWeight: 0.8,
  },
  {
    id: "first_snow_morning",
    terms: ["first snow morning", "first snowfall morning", "snowy cold morning"],
    season: "winter",
    time: "morning",
    environment: "winter",
    energy: 0.3,
    valence: 0.45,
    tension: 0.1,
    nostalgia: 0.4,
    calm: 0.35,
    journeyArc: "slow_burn",
  },
  {
    id: "journey_home_good_night",
    terms: ["journey home after a good night", "ride home after great night out"],
    motion: "transit",
    time: "late_night",
    energy: 0.4,
    valence: 0.62,
    tension: 0.1,
    nostalgia: 0.35,
    calm: 0.2,
    journeyArc: "linear_fall",
    socialContext: "friends",
  },
  {
    id: "journey_home_bad_night",
    terms: ["journey home after a bad night", "uber home after bad night"],
    motion: "transit",
    time: "late_night",
    energy: 0.2,
    valence: 0.28,
    tension: 0.35,
    nostalgia: 0.25,
    calm: 0.15,
    journeyArc: "recovery",
    socialContext: "alone",
  },
];
