/**
 * Scene encyclopedia — moments, not moods.
 * Expand toward 200+ entries; keep compound phrases specific.
 */

import type { SceneEntry } from "./scene-types";
import { SCENE_LIBRARY_EXTENDED } from "./scene-library-extended";
import { SCENE_LIBRARY_MASTER } from "./scene-library-master";

export const SCENE_LIBRARY: SceneEntry[] = [
  // ── Petrol / forecourt (same place, different meaning) ─────────────────────
  {
    id: "petrol_2am",
    terms: [
      "2am petrol station",
      "2 am petrol station",
      "petrol station at 2am",
      "petrol station at 2 am",
      "gas station at 2am",
      "2am gas station",
      "fluorescent forecourt at night",
    ],
    time: "late_night",
    environment: "urban",
    energy: 0.22,
    valence: 0.32,
    tension: 0.58,
    nostalgia: 0.78,
    calm: 0.42,
    journeyArc: "slow_burn",
    qualities: ["liminality", "isolation", "introspection"],
    socialContext: "alone",
    memoryWeight: 0.35,
  },
  {
    id: "petrol_10am",
    terms: [
      "10am petrol station",
      "10 am petrol station",
      "petrol station at 10am",
      "petrol station morning",
      "gas station in the morning",
      "quick stop petrol morning",
    ],
    time: "morning",
    environment: "urban",
    energy: 0.48,
    valence: 0.52,
    tension: 0.28,
    nostalgia: 0.22,
    calm: 0.38,
    journeyArc: "linear_rise",
    qualities: ["routine", "movement", "practical"],
    memoryWeight: 0.1,
  },

  // ── Travel & transit ───────────────────────────────────────────────────────
  {
    id: "airport_sunrise",
    terms: ["airport at sunrise", "airport dawn", "departure lounge morning", "early flight hope"],
    time: "morning",
    environment: "transit",
    motion: "transit",
    energy: 0.42,
    valence: 0.55,
    tension: 0.35,
    nostalgia: 0.28,
    calm: 0.32,
    journeyArc: "linear_rise",
    qualities: ["anticipation", "transition", "optimism"],
    memoryWeight: 0.25,
  },
  {
    id: "airport_late",
    terms: ["airport at night", "red eye airport", "delayed flight alone", "empty terminal late"],
    time: "late_night",
    environment: "transit",
    energy: 0.18,
    valence: 0.38,
    tension: 0.45,
    nostalgia: 0.55,
    calm: 0.28,
    journeyArc: "slow_burn",
    qualities: ["liminality", "waiting", "fatigue"],
    socialContext: "alone",
  },
  {
    id: "late_train_home",
    terms: [
      "late train home",
      "last train home",
      "train home after work",
      "commute home on train late",
      "night train carriage alone",
    ],
    time: "late_night",
    environment: "transit",
    motion: "transit",
    energy: 0.2,
    valence: 0.4,
    tension: 0.32,
    nostalgia: 0.62,
    calm: 0.35,
    journeyArc: "recovery",
    qualities: ["decompression", "mental_recovery", "introspection"],
    lifeSituation: "after_work",
    memoryWeight: 0.4,
  },
  {
    id: "rainy_train_home",
    terms: ["rainy train home", "train window rain going home", "wet commute train"],
    environment: "rainy",
    motion: "transit",
    energy: 0.15,
    valence: 0.42,
    tension: 0.28,
    nostalgia: 0.65,
    calm: 0.4,
    journeyArc: "recovery",
    qualities: ["decompression", "melancholy_warmth"],
    lifeSituation: "after_work",
    memoryWeight: 0.45,
  },
  {
    id: "motorway_rain",
    terms: ["motorway in the rain", "highway rain drive", "wet motorway night", "rain on windshield motorway"],
    environment: "rainy",
    motion: "driving",
    energy: 0.28,
    valence: 0.38,
    tension: 0.42,
    nostalgia: 0.58,
    calm: 0.32,
    journeyArc: "wave",
    qualities: ["focus", "isolation", "motion"],
    memoryWeight: 0.35,
  },
  {
    id: "road_trip_friends",
    terms: ["road trip with friends", "driving with mates", "windows down road trip", "highway trip friends"],
    motion: "driving",
    energy: 0.55,
    valence: 0.68,
    tension: 0.12,
    nostalgia: 0.45,
    calm: 0.2,
    journeyArc: "peak_release",
    qualities: ["freedom", "social_connection", "youth"],
    socialContext: "friends",
    memoryWeight: 0.5,
  },
  {
    id: "driving_nowhere_midnight",
    terms: [
      "driving nowhere at midnight",
      "driving nowhere late",
      "no destination drive night",
      "aimless drive midnight",
    ],
    time: "late_night",
    motion: "driving",
    energy: 0.35,
    valence: 0.45,
    tension: 0.25,
    nostalgia: 0.7,
    calm: 0.38,
    journeyArc: "slow_burn",
    qualities: ["freedom", "reflection", "liminality"],
    socialContext: "alone",
    memoryWeight: 0.55,
  },
  {
    id: "driving_after_argument",
    terms: ["driving after an argument", "drive home after fight", "silent drive after argument"],
    motion: "driving",
    energy: 0.25,
    valence: 0.28,
    tension: 0.65,
    nostalgia: 0.35,
    calm: 0.15,
    journeyArc: "recovery",
    qualities: ["processing", "tension_release"],
    lifeSituation: "conflict",
  },

  // ── Night urban ───────────────────────────────────────────────────────────
  {
    id: "city_after_midnight",
    terms: ["city after midnight", "empty streets after midnight", "downtown dead of night", "urban 3am"],
    time: "late_night",
    environment: "urban",
    energy: 0.2,
    valence: 0.35,
    tension: 0.48,
    nostalgia: 0.72,
    calm: 0.3,
    journeyArc: "slow_burn",
    qualities: ["liminality", "isolation"],
    socialContext: "alone",
  },
  {
    id: "empty_gym_night",
    terms: ["empty gym at night", "gym alone late", "late night workout empty gym"],
    time: "late_night",
    environment: "gym",
    energy: 0.62,
    valence: 0.48,
    tension: 0.35,
    nostalgia: 0.15,
    calm: 0.25,
    journeyArc: "peak_release",
    qualities: ["catharsis", "solo_focus"],
    socialContext: "alone",
  },
  {
    id: "night_drive_alone",
    terms: ["night drive alone", "driving alone at night", "solo night motorway"],
    time: "late_night",
    motion: "driving",
    environment: "urban",
    energy: 0.28,
    valence: 0.38,
    tension: 0.38,
    nostalgia: 0.68,
    calm: 0.32,
    journeyArc: "slow_burn",
    qualities: ["reflection", "introspection"],
    socialContext: "alone",
    memoryWeight: 0.5,
  },

  // ── Day / season / nature ─────────────────────────────────────────────────
  {
    id: "first_warm_spring_day",
    terms: ["first warm day of spring", "first sunny day spring", "spring finally warm", "windows open spring"],
    season: "spring",
    time: "afternoon",
    energy: 0.45,
    valence: 0.72,
    tension: 0.15,
    nostalgia: 0.35,
    calm: 0.35,
    journeyArc: "linear_rise",
    qualities: ["renewal", "hope", "lightness"],
    memoryWeight: 0.4,
  },
  {
    id: "summer_evening_friends",
    terms: [
      "summer evening with friends",
      "warm summer night friends",
      "garden evening friends summer",
      "balcony summer night mates",
    ],
    season: "summer",
    time: "evening",
    energy: 0.42,
    valence: 0.75,
    tension: 0.08,
    nostalgia: 0.55,
    calm: 0.28,
    journeyArc: "wave",
    qualities: ["warmth", "nostalgia_in_progress", "belonging"],
    socialContext: "friends",
    memoryWeight: 0.65,
  },
  {
    id: "beach_sunset",
    terms: ["beach at sunset", "beach sunset", "ocean golden hour", "shoreline dusk"],
    time: "evening",
    environment: "coastal",
    energy: 0.25,
    valence: 0.62,
    tension: 0.12,
    nostalgia: 0.68,
    calm: 0.45,
    journeyArc: "peak_release",
    qualities: ["bittersweet", "reflection"],
    memoryWeight: 0.55,
  },
  {
    id: "autumn_walk",
    terms: ["autumn walk", "fall leaves walk", "crunching leaves october", "cold air autumn walk"],
    season: "autumn",
    motion: "walking",
    environment: "nature",
    energy: 0.2,
    valence: 0.48,
    tension: 0.15,
    nostalgia: 0.75,
    calm: 0.38,
    journeyArc: "slow_burn",
    qualities: ["melancholy_warmth", "memory"],
    memoryWeight: 0.6,
  },
  {
    id: "christmas_lights_night",
    terms: ["christmas lights at night", "xmas lights street", "holiday lights evening"],
    season: "winter",
    time: "evening",
    environment: "urban",
    energy: 0.3,
    valence: 0.65,
    tension: 0.1,
    nostalgia: 0.8,
    calm: 0.35,
    journeyArc: "wave",
    qualities: ["childhood_memory", "warmth"],
    socialContext: "family",
    memoryWeight: 0.75,
  },

  // ── Work & study rhythms ───────────────────────────────────────────────────
  {
    id: "friday_after_work",
    terms: [
      "finishing work on a friday",
      "friday after work",
      "clocking off friday",
      "end of week relief",
    ],
    time: "evening",
    energy: 0.5,
    valence: 0.68,
    tension: 0.05,
    nostalgia: 0.2,
    calm: 0.25,
    journeyArc: "linear_rise",
    qualities: ["release", "anticipation_weekend"],
    lifeSituation: "after_work",
  },
  {
    id: "studying_1am",
    terms: ["studying at 1am", "library 1am", "exam cram 1am", "revision through the night"],
    time: "late_night",
    environment: "library",
    energy: 0.22,
    valence: 0.35,
    tension: 0.55,
    nostalgia: 0.25,
    calm: 0.2,
    journeyArc: "linear_rise",
    qualities: ["pressure", "determination"],
    socialContext: "alone",
  },
  {
    id: "studying_cafe",
    terms: ["studying in a café", "studying in a cafe", "laptop café study", "coffee shop revision"],
    environment: "social_indoor",
    energy: 0.18,
    valence: 0.45,
    tension: 0.38,
    nostalgia: 0.3,
    calm: 0.42,
    journeyArc: "flat",
    qualities: ["focus", "ambient_comfort"],
  },
  {
    id: "sunday_evening_reset",
    terms: ["sunday evening reset", "sunday night reset", "pre monday calm", "sunday scaries soft"],
    time: "evening",
    energy: 0.12,
    valence: 0.42,
    tension: 0.35,
    nostalgia: 0.45,
    calm: 0.55,
    journeyArc: "recovery",
    qualities: ["reset", "quiet_acceptance"],
  },

  // ── Weather walks & drives ─────────────────────────────────────────────────
  {
    id: "rainy_city_walk",
    terms: ["walking through a city in the rain", "rainy city walk", "urban rain walk alone"],
    environment: "rainy",
    motion: "walking",
    energy: 0.15,
    valence: 0.4,
    tension: 0.25,
    nostalgia: 0.6,
    calm: 0.42,
    journeyArc: "slow_burn",
    qualities: ["melancholy_beauty", "introspection"],
    socialContext: "alone",
    memoryWeight: 0.45,
  },
  {
    id: "driving_through_fog",
    terms: ["driving through fog", "fog on the road", "misty drive alone", "headlights fog"],
    motion: "driving",
    energy: 0.2,
    valence: 0.38,
    tension: 0.52,
    nostalgia: 0.55,
    calm: 0.28,
    journeyArc: "slow_burn",
    qualities: ["uncertainty", "focus"],
  },
  {
    id: "traffic_jam",
    terms: ["sitting in traffic", "stuck in traffic", "traffic jam frustration"],
    motion: "driving",
    energy: 0.15,
    valence: 0.32,
    tension: 0.62,
    nostalgia: 0.1,
    calm: 0.05,
    journeyArc: "wave",
    qualities: ["irritation", "stasis"],
  },

  // ── Social moments ─────────────────────────────────────────────────────────
  {
    id: "post_gym_confidence",
    terms: ["post gym confidence", "after workout high", "leaving gym empowered"],
    environment: "gym",
    energy: 0.68,
    valence: 0.72,
    tension: 0.15,
    nostalgia: 0.05,
    calm: 0.2,
    journeyArc: "peak_release",
    qualities: ["confidence", "physical_release"],
    socialContext: "alone",
  },
  {
    id: "date_night_walk",
    terms: ["date night walk", "evening walk date", "holding hands walk evening"],
    time: "evening",
    motion: "walking",
    energy: 0.28,
    valence: 0.72,
    tension: 0.18,
    nostalgia: 0.25,
    calm: 0.4,
    journeyArc: "wave",
    qualities: ["romance", "tenderness"],
    socialContext: "partner",
  },
  {
    id: "party_after_friends",
    terms: ["after seeing friends", "driving after party", "1am after friends", "post party drive reflection"],
    time: "late_night",
    motion: "driving",
    energy: 0.32,
    valence: 0.55,
    tension: 0.2,
    nostalgia: 0.5,
    calm: 0.35,
    journeyArc: "recovery",
    qualities: ["afterglow", "reflection"],
    socialContext: "friends",
    lifeSituation: "social_recovery",
  },

  // ── Life situations (matter more than place) ───────────────────────────────
  {
    id: "life_breakup",
    terms: ["breakup", "broke up", "just broke up", "post breakup", "heart broken"],
    energy: 0.15,
    valence: 0.22,
    tension: 0.55,
    nostalgia: 0.7,
    calm: 0.2,
    journeyArc: "recovery",
    qualities: ["grief", "processing"],
    lifeSituation: "breakup",
    memoryWeight: 0.5,
  },
  {
    id: "life_starting_over",
    terms: ["starting over", "fresh start", "new chapter", "beginning again"],
    energy: 0.38,
    valence: 0.55,
    tension: 0.4,
    nostalgia: 0.25,
    calm: 0.25,
    journeyArc: "linear_rise",
    qualities: ["hope", "courage"],
    lifeSituation: "starting_over",
  },
  {
    id: "life_burnout",
    terms: ["burnout", "burnt out completely", "can't keep going", "emotionally exhausted work"],
    energy: 0.08,
    valence: 0.28,
    tension: 0.45,
    nostalgia: 0.2,
    calm: 0.15,
    journeyArc: "recovery",
    qualities: ["depletion"],
    lifeSituation: "burnout",
  },
  {
    id: "life_missing_someone",
    terms: ["missing someone", "miss them so much", "long distance missing", "wish you were here"],
    energy: 0.12,
    valence: 0.3,
    tension: 0.35,
    nostalgia: 0.85,
    calm: 0.25,
    journeyArc: "slow_burn",
    qualities: ["longing"],
    lifeSituation: "missing_someone",
    memoryWeight: 0.7,
  },
  {
    id: "life_falling_in_love",
    terms: ["falling in love", "new love", "can't stop thinking about them", "butterflies"],
    energy: 0.42,
    valence: 0.78,
    tension: 0.25,
    nostalgia: 0.15,
    calm: 0.2,
    journeyArc: "wave",
    qualities: ["euphoria", "vulnerability"],
    lifeSituation: "falling_in_love",
  },
  {
    id: "life_grieving",
    terms: ["grieving", "mourning", "lost someone", "funeral week"],
    energy: 0.1,
    valence: 0.18,
    tension: 0.4,
    nostalgia: 0.75,
    calm: 0.35,
    journeyArc: "slow_burn",
    qualities: ["grief", "honouring"],
    lifeSituation: "grieving",
    memoryWeight: 0.65,
  },
  {
    id: "life_promotion",
    terms: ["got promoted", "promotion day", "big win at work", "achievement unlocked"],
    energy: 0.55,
    valence: 0.8,
    tension: 0.2,
    nostalgia: 0.1,
    calm: 0.15,
    journeyArc: "peak_release",
    qualities: ["pride", "celebration"],
    lifeSituation: "promotion",
  },
  {
    id: "life_moving_house",
    terms: ["moving house", "moving day", "packing boxes", "new flat keys"],
    energy: 0.35,
    valence: 0.45,
    tension: 0.55,
    nostalgia: 0.55,
    calm: 0.1,
    journeyArc: "wave",
    qualities: ["transition", "bittersweet"],
    lifeSituation: "moving",
  },

  // ── Memory-heavy ───────────────────────────────────────────────────────────
  {
    id: "memory_summer_evenings",
    terms: ["summer evenings childhood", "hot summer nights growing up", "late summer evening memory"],
    season: "summer",
    time: "evening",
    energy: 0.3,
    valence: 0.6,
    tension: 0.08,
    nostalgia: 0.88,
    calm: 0.35,
    journeyArc: "wave",
    qualities: ["memory", "bittersweet"],
    memoryWeight: 0.9,
  },
  {
    id: "memory_school_years",
    terms: ["school years", "high school nostalgia", "teenage years music"],
    energy: 0.28,
    valence: 0.5,
    tension: 0.15,
    nostalgia: 0.92,
    calm: 0.25,
    journeyArc: "wave",
    qualities: ["memory", "youth"],
    memoryWeight: 0.95,
  },
  {
    id: "memory_late_night_gaming",
    terms: ["late night gaming", "gaming till 3am", "minecraft nights", "online friends late gaming"],
    time: "late_night",
    energy: 0.35,
    valence: 0.55,
    tension: 0.2,
    nostalgia: 0.82,
    calm: 0.2,
    journeyArc: "peak_release",
    qualities: ["memory", "comfort"],
    socialContext: "friends",
    memoryWeight: 0.85,
  },
  {
    id: "memory_family_holiday",
    terms: ["family holiday", "childhood holiday", "car holiday as a kid"],
    energy: 0.38,
    valence: 0.65,
    tension: 0.05,
    nostalgia: 0.9,
    calm: 0.3,
    journeyArc: "wave",
    qualities: ["memory", "warmth"],
    socialContext: "family",
    memoryWeight: 0.9,
  },
  {
    id: "memory_long_drives",
    terms: ["long drives nostalgia", "childhood road trip", "dad driving music"],
    motion: "driving",
    energy: 0.32,
    valence: 0.52,
    tension: 0.12,
    nostalgia: 0.88,
    calm: 0.32,
    journeyArc: "slow_burn",
    qualities: ["memory", "journey"],
    memoryWeight: 0.88,
  },

  ...SCENE_LIBRARY_EXTENDED,
  ...SCENE_LIBRARY_MASTER,
];
