export type SceneFamily =
  | "MOVEMENT"
  | "PRIVATE"
  | "SOCIAL"
  | "LIFE_TRANSITIONS"
  | "NOSTALGIA"
  | "ACHIEVEMENT";

export const SCENE_FAMILIES: Record<string, SceneFamily> = {
  LATE_NIGHT_SOLITARY_JOURNEY: "MOVEMENT",
  REFLECTIVE_AVOIDANCE_JOURNEY: "MOVEMENT",
  DEPARTURE_WALK: "MOVEMENT",
  NOCTURNAL_ESCAPE_DRIVE: "MOVEMENT",
  COASTAL_OPEN_ROAD: "MOVEMENT",
  MENTAL_RESET_WALK: "MOVEMENT",
  INTROSPECTIVE_PRIVACY: "PRIVATE",
  DOMESTIC_QUIET: "PRIVATE",
  UK_GREY_SUNDAY_INDOORS: "PRIVATE",
  WEATHER_REFLECTION: "PRIVATE",
  QUIET_AFTERMATH: "SOCIAL",
  FRESH_START_ALONE: "LIFE_TRANSITIONS",
  SUMMER_TRANSITION: "LIFE_TRANSITIONS",
  NOSTALGIC_RETURN: "NOSTALGIA",
};

export const FAMILY_BOOST = 28;
